<script>
    /*
     $(function() {
     $("#searchbox").click(function() {
     var options = {percent: 0};
     $("#searchbox").hide('slide', options, 1000);
     return false;
     });
     
     });
     */
</script>
<div class="toggler noprint">
    <div id="searchbox" class="ui-widget-content" style="width: 600px;">
        <table width="100%">
            <thead>
                <tr>
                    <th colspan="2"><?php print $this->T("search_debtor_c") ?></th>
                </tr>
            </thead>
            <form method=post action='<?php echo $this->url(); ?>'>
                <?php echo $this->SearchBox->search_debtor->renderViewHelper(); ?>
                <tr>
                    <td><?php $this->T("name_c"); ?></td>
                    <td><?php echo $this->SearchBox->name->renderViewHelper(); ?></td>
                </tr>
                <tr> 
                    <td><?php $this->T("vatnr_c"); ?></td>
                    <td><?php echo $this->SearchBox->vat_no->renderViewHelper(); ?></td>
                </tr>
                <tr> 
                    <td><?php $this->T("address_c"); ?></td>
                    <td><?php echo $this->SearchBox->address->renderViewHelper(); ?></td>
                </tr>
                <tr> 
                    <td><?php $this->T("zipcode_c"); ?></td>
                    <td><?php echo $this->SearchBox->zip_code->renderViewHelper(); ?> <?php echo $this->SearchBox->city->renderViewHelper(); ?></td>
                </tr>
                <tr>
                    <td colspan="2" align="right"><?php echo $this->SearchBox->submit->renderViewHelper(); ?></td>
                </tr>
        </table>
        </form>
    </div>
</div>
<br>
<?php if (!empty($this->results)) {  $index=0;?>
    <div class=noprint>
        <h3>
            <?php echo $this->totals->COUNTER ?> <?php $this->T("results_found_c") ?>
            <?php if ($this->onlyFirst) { ?>
                <?php $this->T("only_first_c", $this->onlyFirst) ?>
            <?php } ?>
        </h3>
    </div>
    <table id="data" class="tablesorter ws_data_table" width="100%">
        <thead>
            <tr>
                <th><?php $this->T("name_c"); ?></th>
                <th><?php $this->T("vatnr_c"); ?></th>
                <th><?php $this->T("address_c"); ?></th>
                <th><?php $this->T("zipcode_c"); ?></th>
                <th><?php $this->T("open_files_c"); ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->NAME ?></td>
                <td><?php echo $row->VATNR ?></td>
                <td><?php echo $row->ADDRESS ?></td>
                <td><?php echo $row->ZIP_CODE ?> <?php echo $row->CITY ?></td>
                <td><?php echo $row->OPEN_FILES ?></td>
               <td><span title ="<?php $this->T("view_debtor_c") ?>" onClick="newscreen('<?php echo $row->NAME ?>', '<?php echo $this->location() ?>/debtor-detail/view/index/<?php echo $index ?>')" class="ui-icon ui-icon-zoomin"></span></td>
            </tr>
        <?php $index++; } ?>
    </table>
<?php } ?>
