<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php echo count($this->results) ?> resultaten gevonden</h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
						<tr>
							<td><?php $this->T('Code_c') ?></td>
							<td><?php $this->T('train_type_c') ?></td>
							<td><?php $this->T('order_c') ?></td>
							<td><?php $this->T('description_c') ?></td>
							<td><?php $this->T('Open_files_c') ?></td>
							<td><?php $this->T('days_c') ?></td>
							<td><?php $this->T('payments_c') ?></td>
							<td><?php $this->T('other_actions_c') ?></td>
							<td><?php $this->T('set_action_c') ?></td>
							<td><?php $this->T('actief_c') ?></td>
							<td></td>
							<td></td>
						</tr>
                    </thead>
					<tbody>
						<?php if (!empty($this->results)) { ?>
							<?php foreach ($this->results as $row) { ?>
								<tr>
									<td><?php echo $row->CODE ?></td>
									<td><?php echo $row->TRAIN_TYPE ?></td>
									<td><?php echo $row->ORDER_CYCLE ?></td>
									<td><?php echo $row->DESCRIPTION ?></td>
									<td><?php echo $row->OPEN_FILES ?></td>
									<td><?php echo $row->DAYS ?></td>
									<td><?php echo $row->PAYMENTS ?></td>
									<td><?php echo $row->OTHER_ACTIONS ?></td>
									<td><?php echo $row->ACTION_CODE ?></td>
									<td><?php echo $row->ACTIEF ?></td>
									<td><a href="<?php echo $this->location() ?>/settings-traject/edit/id/<?php echo $row->ID ?>" ><li class="fa fa-search-plus fa-fw"></li></td>
									<td>
										<?php echo $this->Delete($this->location()."/settings-traject/view/delete/" . $row->ID , $row->CODE) ?>
									</td>

								</tr>
							<?php } ?>
						<?php } else { ?>
							<tr>
								<td colspan="5" class="no_results">
									<?php $this->T("no_results_c"); ?>
								</td>
							</tr>
						<?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->
		  