<?php if ($this->form) { ?>
<div class="aaa-theme-flex-row flex-content-row">
    <div class="aaa-theme-content-widget white-bg col-1 text-center">
        <?php echo $this->form ?>
    </div>
</div>
<?php } ?>

<div class="aaa-theme-flex-row flex-content-row aaa-theme-overflow-hidden"> <!-- overflow hidden for iPad mini landscape view-->
            <div class="col-1">
              <div class="aaa-theme-content-widget white-bg col-1 text-center">
			  <br>
<?php if (!empty($this->aging)): ?>
    <style>
        #chartdiv {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }
        #chartdiv2 {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }

        #legenddiv {
            width: 100%;
            font-size: 11px;
            position: relative;
        }
        #legenddiv2 {
            width: 100%;
            font-size: 11px;
            position: relative;
        }

        a.thead:link, a.thead:visited {
            text-decoration: none;
            color: #000000;
        }

        a.thead:hover, a.thead:active {
            text-decoration: none;
            color: #e75a21;
        }

        a.tbody:link, a.tbody:visited {
            text-decoration: none;
            color: #000000;
        }

        a.tbody:hover, a.tbody:active {
            text-decoration: none;
            color: #ffffff;
        }
    </style>

    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/pie.js"></script>

 <div class="table-responsive">
					<table class="table table-striped table-bordered">
					<thead>

                <thead>
                <tr>
                    <td><?php echo $this->T('type_c') ?></td>
                    <td><a class="thead" href="export-aging/period/1q">1Q</a></td>
                    <td><a class="thead" href="export-aging/period/2q">2Q</a></td>
                    <td><a class="thead" href="export-aging/period/3q">3Q</a></td>
                    <td><a class="thead" href="export-aging/period/4q">4Q</a></td>
                    <td><a class="thead" href="export-aging/period/1y">1Y</a></td>
                    <td><a class="thead" href="export-aging/period/2y">2Y</a></td>
                    <td><a class="thead" href="export-aging/period/3y">3Y</a></td>
                    <td><a class="thead" href="export-aging/period/all"><?php echo $this->T('Total_c') ?></a></td>
                </tr>
                </thead>
                <tbody>

                <?php
                if (!empty($this->selectionData['GROUP_BY'])){
                    $groupBy = "/groupby/".$this->selectionData['GROUP_BY'];
                } else { $groupBy = "";}

                if (!empty($this->selectionData['COLLECTOR_ID'])){
                    $collectorId = "/collector/".$this->selectionData['COLLECTOR_ID'];
                } else { $collectorId = "";}

                if (!empty($this->selectionData['CONTRACT_UNDERWRITER'])){
                    $underWriter = "/underwriter/".$this->selectionData['CONTRACT_UNDERWRITER'];
                } else { $underWriter = "";}

                if (!empty($this->selectionData['CONTRACT_LINEOFBUSINESS'])){
                    $lob = "/lob/".$this->selectionData['CONTRACT_LINEOFBUSINESS'];
                } else { $lob = "";}

                ?>

                <?php foreach ($this->aging as $type => $row): ?>

                    <tr class="table_aging_row">
                        <td>
                            <a class="tbody" href="export-aging/period/all/type/<?php echo $type; ?>"><?php echo $type ?></a>
                        </td>
                        <td align="right">
                            <a class="tbody" href="export-aging/period/1q/type/<?php echo $type; ?><?php echo $groupBy; ?><?php echo $collectorId; ?><?php echo $underWriter; ?><?php echo $lob; ?>">
                            <?php echo $this->amount($row['1Q']->SUM); ?>
                            </a>
                        </td>
                        <td align="right">
                            <a class="tbody" href="export-aging/period/2q/type/<?php echo $type; ?><?php echo $groupBy; ?><?php echo $collectorId; ?><?php echo $underWriter; ?><?php echo $lob; ?>">
                            <?php echo $this->amount($row['2Q']->SUM); ?>
                            </a>
                        </td>
                        <td align="right">
                            <a class="tbody" href="export-aging/period/3q/type/<?php echo $type; ?><?php echo $groupBy; ?><?php echo $collectorId; ?><?php echo $underWriter; ?><?php echo $lob; ?>">
                            <?php echo $this->amount($row['3Q']->SUM); ?>
                            </a>
                        </td>
                        <td align="right">
                            <a class="tbody" href="export-aging/period/4q/type/<?php echo $type; ?><?php echo $groupBy; ?><?php echo $collectorId; ?><?php echo $underWriter; ?><?php echo $lob; ?>">
                            <?php echo $this->amount($row['4Q']->SUM); ?>
                            </a>
                        </td>
                        <td align="right">
                            <a class="tbody" href="export-aging/period/1y/type/<?php echo $type; ?><?php echo $groupBy; ?><?php echo $collectorId; ?><?php echo $underWriter; ?><?php echo $lob; ?>">
                            <?php echo $this->amount($row['1Y']->SUM); ?>
                            </a>
                        </td>
                        <td align="right">
                            <a class="tbody" href="export-aging/period/2y/type/<?php echo $type; ?><?php echo $groupBy; ?><?php echo $collectorId; ?><?php echo $underWriter; ?><?php echo $lob; ?>">
                            <?php echo $this->amount($row['2Y']->SUM); ?>
                            </a>
                        </td>
                        <td align="right">
                            <a class="tbody" href="export-aging/period/3y/type/<?php echo $type; ?><?php echo $groupBy; ?><?php echo $collectorId; ?><?php echo $underWriter; ?><?php echo $lob; ?>">
                            <?php echo $this->amount($row['3Y']->SUM); ?>
                            </a>
                        </td>
                        <td align="right">
                            <?php echo $this->amount($row['1Q']->SUM + $row['2Q']->SUM + $row['3Q']->SUM + $row['4Q']->SUM + $row['1Y']->SUM + $row['2Y']->SUM + $row['3Y']->SUM); ?>
                        </td>
                    </tr>
                    <?php
                    $total['Q1'] += $row['1Q']->SUM;
                    $total['Q2'] += $row['2Q']->SUM;
                    $total['Q3'] += $row['3Q']->SUM;
                    $total['Q4'] += $row['4Q']->SUM;
                    $total['1Y'] += $row['1Y']->SUM;
                    $total['2Y'] += $row['2Y']->SUM;
                    $total['3Y'] += $row['3Y']->SUM;
                    ?>
                <?php endforeach; ?>
                <tfoot>
                <tr>
                    <td><a class="thead" href="export-aging/period/all"><?php echo $this->T('Total_c') ?></a></td>
                    <td align="right"><?php echo $this->amount($total['Q1']); ?></td>
                    <td align="right"><?php echo $this->amount($total['Q2']); ?></td>
                    <td align="right"><?php echo $this->amount($total['Q3']); ?></td>
                    <td align="right"><?php echo $this->amount($total['Q4']); ?></td>
                    <td align="right"><?php echo $this->amount($total['1Y']); ?></td>
                    <td align="right"><?php echo $this->amount($total['2Y']); ?></td>
                    <td align="right"><?php echo $this->amount($total['3Y']); ?></td>
                    <td align="right"><?php echo $this->amount( ($total['Q1'] + $total['Q2'] + $total['Q3'] + $total['Q4'] + $total['1Y'] + $total['2Y'] + $total['3Y'])); ?></td>
                </tr>
                </tfoot>
                </tbody>
            </table>
            <p style="color: #777777; margin-top: 10px;">
                (*) <?php echo $this->T('exchengerate_c') ?>:
                <?php foreach ($this->ratings as $currency => $attributes): ?>
                    <?php if($currency == 'EUR'){continue; } ?>
                    EUR x
                    <?php echo $currency; ?> = <?php echo $attributes['RATE']; ?> &nbsp;&nbsp;&nbsp;
                <?php endforeach; ?>
            </p>
	                </div>
              </div>
            </div>
          </div>

		       <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">

                <script>
                    var chartData = [
                        <?php foreach ($total as $type => $value): ?>
                        {
                            "titel": "<?php echo $type ?>",
                            "waarde": <?php echo $value ?>
                        },
                        <?php endforeach ?>
                        ];

                    for (var i in chartData) {
                        chartData[i].absValue = Math.abs(chartData[i].waarde);
                    }

                    var chart = AmCharts.makeChart("chartdiv2", {
                        "type": "pie",
                        "theme": "none",
                        "colors": ["#598CB4","#C0605D","#9DB370", "#8B74A0", "#4CACBD", "#E69A5F", "#A5BBD6", "#FF0000", "#FF0000"],
                        "dataProvider": chartData,
                        "valueField": "absValue",
                        "titleField": "titel",
                        "balloonText": "[[title]]: [[percents]]% ([[waarde]])",
                        "labelText": "[[title]]: [[percents]]% ([[waarde]])"
                    });
                    var legend = new AmCharts.AmLegend();
                </script>

                <div id="chartdiv2"></div>
              </div>
            </div>
          </div>

<?php else: ?>
    <?php echo $this->Message($this->G("no_results_c")); ?>
<?php endif; ?>