<?php if ($this->form) { ?>
<div class="aaa-theme-flex-row flex-content-row">
    <div class="aaa-theme-content-widget white-bg col-1 text-center">
        <?php echo $this->form ?>
    </div>
</div>
<?php } ?>

<div class="aaa-theme-flex-row flex-content-row aaa-theme-overflow-hidden"> <!-- overflow hidden for iPad mini landscape view-->
            <div class="col-1">
              <div class="aaa-theme-content-widget white-bg col-1 text-center">
			  <br>
<?php if (!empty($this->aging)): ?>
    <style>
        #chartdiv {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }
        #chartdiv2 {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }
    </style>
    <style>
        #legenddiv {
            width: 100%;
            font-size: 11px;
            position: relative;
        }
        #legenddiv2 {
            width: 100%;
            font-size: 11px;
            position: relative;
        }
    </style>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/pie.js"></script>

 <div class="table-responsive">
					<table class="table table-striped table-bordered">
					<thead>

                <thead>
                <tr>
                    <td><?php echo $this->T('type_c') ?></td>
                    <td>1Q</td>
                    <td>2Q</td>
                    <td>3Q</td>
                    <td>4Q</td>
                    <td>1Y</td>
                    <td>2Y</td>
                    <td>3Y</td>
                    <td><?php echo $this->T('Total_c') ?></td>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->aging as $type => $row): ?>
                    <tr>
                        <td><?php echo $type ?></td>
                        <td align="right"><?php echo $this->amount($row['1Q']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['2Q']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['3Q']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['4Q']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['1Y']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['2Y']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['3Y']->SUM); ?></td>
                        <td align="right"	><?php echo $this->amount($row['1Q']->SUM + $row['2Q']->SUM + $row['3Q']->SUM + $row['4Q']->SUM + $row['1Y']->SUM + $row['2Y']->SUM + $row['3Y']->SUM); ?></td>
                    </tr>
                    <?php
                    $total['Q1'] += $row['1Q']->SUM;
                    $total['Q2'] += $row['2Q']->SUM;
                    $total['Q3'] += $row['3Q']->SUM;
                    $total['Q4'] += $row['4Q']->SUM;
                    $total['1Y'] += $row['1Y']->SUM;
                    $total['2Y'] += $row['2Y']->SUM;
                    $total['3Y'] += $row['3Y']->SUM;
                    ?>
                <?php endforeach; ?>
                <tfoot>
                <tr>
                    <td><?php echo $this->T('Total_c') ?></td>
                    <td align="right"><?php echo $this->amount($total['Q1']); ?></td>
                    <td align="right"><?php echo $this->amount($total['Q2']); ?></td>
                    <td align="right"><?php echo $this->amount($total['Q3']); ?></td>
                    <td align="right"><?php echo $this->amount($total['Q4']); ?></td>
                    <td align="right"><?php echo $this->amount($total['1Y']); ?></td>
                    <td align="right"><?php echo $this->amount($total['2Y']); ?></td>
                    <td align="right"><?php echo $this->amount($total['3Y']); ?></td>
                    <td align="right"><?php echo $this->amount( ($total['Q1'] + $total['Q2'] + $total['Q3'] + $total['Q4'] + $total['1Y'] + $total['2Y'] + $total['3Y'])); ?></td>
                </tr>
                </tfoot>
                </tbody>
            </table>

	                </div>
              </div>
            </div>
          </div>

		       <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">

                <script>
                    var chart = AmCharts.makeChart("chartdiv2", {
                        "type": "pie",
                        "theme": "none",
                        "colors": ["#598CB4","#C0605D","#9DB370", "#8B74A0", "#4CACBD", "#E69A5F", "#A5BBD6", "#FF0000", "#FF0000"],
                        "dataProvider": [
                            <?php foreach ($total as $type => $value): ?>
                            {
                                "titel": "<?php echo $type ?>",
                                "waarde": <?php echo $value ?>
                            },
                            <?php endforeach ?>
                        ],
                        "valueField": "waarde",
                        "titleField": "titel",
                    });
                    var legend = new AmCharts.AmLegend();
                </script>

                <div id="chartdiv2"></div>
              </div>
            </div>
          </div>

<?php else: ?>
    <?php echo $this->Message($this->G("no_results_c")); ?>
<?php endif; ?>