<?php if (!$this->isClient): ?>
    <script>
        $(function () {
            $('#clientId').change(function () {
                $(this).parent('form').submit();
            });
        })
    </script>
    <form method="get">
        <select name="clientId" id="clientId">
            <?php foreach ($this->clients as $client): ?>
                <option
                    value="<?php echo $client->CLIENT_ID ?>" <?php echo $this->clientId == $client->CLIENT_ID ? 'selected="selected"' : '' ?>>
                    <?php echo $client->NAME ?>
                </option>
            <?php endforeach ?>
        </select>
    </form>
    <br>
<?php endif; ?>
<?php if (!empty($this->aging)): ?>
    <style>
        #chartdiv {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }
        #chartdiv2 {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }
    </style>
    <style>
        #legenddiv {
            width: 100%;
            font-size: 11px;
            position: relative;
        }
        #legenddiv2 {
            width: 100%;
            font-size: 11px;
            position: relative;
        }
    </style>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/pie.js"></script>

            <!--<td width="50%">
                <table class="ws_data_table">
                    <thead>
                    <tr>
                        <th><?php echo $this->T('type_c') ?></th>
                        <th><?php echo $this->T('not_due_c') ?></th>
                        <th>1-90 <?php $this->T("days_c")?></th>
                        <th>91-100 <?php $this->T("days_c")?></th>
                        <th>101-365 <?php $this->T("days_c")?></th>
                        <th>366-.. <?php $this->T("days_c")?></th>
                        <th><?php echo $this->T('Total_c') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->aging as $type => $row): ?>
                        <tr>
                            <td><?php echo $type ?></td>
                            <td><?php echo $row['0']->COUNT; ?></td>
                            <td><?php echo $row['1-90']->COUNT; ?></td>
                            <td><?php echo $row['91-100']->COUNT; ?></td>
                            <td><?php echo $row['101-365']->COUNT; ?></td>
                            <td><?php echo $row['365+']->COUNT; ?></td>
                            <td class="label"><?php echo $row['0']->COUNT + $row['1-91']->COUNT + $row['91-100']->COUNT + $row['101-365']->COUNT + $row['365+']->COUNT; ?></td>
                        </tr>
                        <?php
                        $count['0'] += $row['0']->COUNT;
                        $count['1-90'] += $row['1-90']->COUNT;
                        $count['91-100'] += $row['91-100']->COUNT;
                        $count['101-365'] += $row['101-365']->COUNT;
                        $count['365+'] += $row['365+']->COUNT;
                        ?>
                    <?php endforeach; ?>
                    <tfoot>
                    <tr>
                        <td><?php echo $this->T('Total_c') ?></td>
                        <td><?php echo $count['0']*1 ?></td>
                        <td><?php echo $count['1-90']*1 ?></td>
                        <td><?php echo $count['91-100']*1 ?></td>
                        <td><?php echo $count['101-365']*1 ?></td>
                        <td><?php echo $count['365+']*1 ?></td>
                        <td><?php echo $count['0'] + $count['1-90'] + $count['91-100'] + $count['101-365'] + $count['365+']; ?></td>
                    </tr>
                    </tfoot>
                    </tbody>
                </table>
            -->
            <table class="ws_data_table" width="100%">
                <thead>
                <tr>
                    <th><?php echo $this->T('type_c') ?></th>
                    <th><?php echo $this->T('not_due_c') ?></th>
                    <th>< 1 M</th>
                    <th>< 3 M</th>
                    <th>< 6 M</th>
                    <th>< 12 M</th>
                    <th>< 24 M</th>
                    <th>> 24 M</th>
                    <th><?php echo $this->T('Total_c') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->aging as $type => $row): ?>
                    <tr>
                        <td><?php echo $type ?></td>
                        <td align="right"><?php echo $this->amount($row['0']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['1-30']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['31-90']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['91-180']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['181-365']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['366-730']->SUM); ?></td>
                        <td align="right"><?php echo $this->amount($row['731+']->SUM); ?></td>
                        <td align="right" class="label"><?php echo $this->amount($row['0']->SUM + $row['1-30']->SUM + $row['31-90']->SUM + $row['91-180']->SUM + $row['181-365']->SUM + $row['366-730']->SUM + $row['731+']->SUM); ?></td>
                    </tr>
                    <?php
                    $total['0'] += $row['0']->SUM;
                    $total['1-30'] += $row['1-30']->SUM;
                    $total['31-90'] += $row['31-90']->SUM;
                    $total['91-180'] += $row['91-180']->SUM;
                    $total['181-365'] += $row['181-365']->SUM;
                    $total['366-730'] += $row['366-730']->SUM;
                    $total['731+'] += $row['731+']->SUM;
                    ?>
                <?php endforeach; ?>
                <tfoot>
                <tr>
                    <td><?php echo $this->T('Total_c') ?></td>
                    <td align="right"><?php echo $this->amount($total['0']); ?></td>
                    <td align="right"><?php echo $this->amount($total['1-30']); ?></td>
                    <td align="right"><?php echo $this->amount($total['31-90']); ?></td>
                    <td align="right"><?php echo $this->amount($total['91-180']); ?></td>
                    <td align="right"><?php echo $this->amount($total['181-365']); ?></td>
                    <td align="right"><?php echo $this->amount($total['366-730']); ?></td>
                    <td align="right"><?php echo $this->amount($total['731+']); ?></td>
                    <td align="right"><?php echo $this->amount( ($total['0'] + $total['1-30'] + $total['31-90'] + $total['91-180'] + $total['181-365'] + $total['181-365'] + $total['366-730'] + $total['731+'])); ?></td>
                </tr>
                </tfoot>
                </tbody>
            </table>
    <table width="100%">
        <tr>
            <td>
                <script>
                    var chart = AmCharts.makeChart("chartdiv2", {
                        "type": "pie",
                        "theme": "none",
                        "dataProvider": [
                            <?php foreach ($total as $type => $value): ?>
                            {
                                "titel": "<?php echo $type ?> <?php $this->T("days_c")?>",
                                "waarde": <?php echo $value ?>
                            },
                            <?php endforeach ?>
                        ],
                        "valueField": "waarde",
                        "titleField": "titel",
                    });
                    var legend = new AmCharts.AmLegend();
                </script>

                <div id="chartdiv2"></div>

            </td>
        </tr>
    </table>
<?php else: ?>
    <?php echo $this->Message($this->G("no_results_c")); ?>
<?php endif; ?>