    	<script>
		$(document).ready(function() {
			$(".various").fancybox({
				fitToView	: false,
				width		: '100%',
				height		: '100%',
				autoSize	: false,
				closeClick	: false,
				openEffect	: 'none',
				closeEffect	: 'none'
			});
		});
		</script>
		
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
    <?php if (!empty($this->results)) {
    $index = 0;
    ?>            	

                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
						<td><?php print $this->T("referenceclient_c") ?></td>
						<td><?php print $this->T("debtor_c") ?></td>
						<td><?php print $this->T("payable_c") ?></td>
						<td>90 - 180 <?php print $this->T("days_c") ?></td>
						<td>180 - 365 <?php print $this->T("days_c") ?></td>
						<td>+ 365 <?php print $this->T("days_c") ?></td>
						<td>15% <?php print $this->T("provision_c") ?></td>
						<td>50% <?php print $this->T("provision_c") ?></td>
						<td>100% <?php print $this->T("provision_c") ?></td>
						<td>&nbsp;</td>
                      </tr>
                    </thead>
                    <tbody>
       <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->REFERENCE ?></td>
                <td><?php echo $row->DEBTOR_NAME ?></td>
                <td align="right"><?php echo $this->amount($row->SALDO) ?></td>
                <td align="right"><?php echo $this->amount($row->KLASSE1) ?></td>
                <td align="right"><?php echo $this->amount($row->KLASSE2) ?></td>
                <td align="right"><?php echo $this->amount($row->KLASSE3) ?></td>
                <td align="right"><?php echo $this->amount($row->PROVISION1) ?></td>
                <td align="right"><?php echo $this->amount($row->PROVISION2) ?></td>
                <td align="right"><?php echo $this->amount($row->PROVISION3) ?></td>
                <td><a class="various fancybox.iframe" href="<?php echo $this->location() ?>/file-detail/view/fileId/<?php echo $row->FILE_ID ?>"><li class="fa fa-search-plus fa-fw"></li></a></td>
            </tr>
            <?php $index++;
        }
        ?>
    </table>
<?php } ?>
                </div>                          
              </div>
            </div>  
          </div> 
<!-- Second row ends -->