<div class="aaa-theme-flex-row flex-content-row aaa-theme-overflow-hidden"> <!-- overflow hidden for iPad mini landscape view-->
            <div class="col-1">              
              <div class="aaa-theme-content-widget white-bg col-1 text-center">
              
<?php if (!$this->isClient): ?>
    <script>
        $(function () {
            $('#clientId').change(function () {
                $(this).closest('form').submit();
            });
        })
    </script>
    <form method="get">
        <select name="clientId" id="clientId">
            <?php foreach ($this->clients as $client): ?>
                <option
                    value="<?php echo $client->CLIENT_ID ?>" <?php echo $this->clientId == $client->CLIENT_ID ? 'selected="selected"' : '' ?>>
                    <?php echo $client->NAME ?>
                </option>
            <?php endforeach ?>
        </select>
    </form>
    <br>
<?php endif; ?>
<style>
    #chartdivLine {
        width: 100%;
        height: 400px;
        font-size: 11px;
        position: relative;
    }
</style>
<style>
    #legenddiv {
        width: 100%;
        font-size: 11px;
        position: relative;
    }
</style>
<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/serial.js"></script>

<?php if (!empty($this->dso)): ?>
    <div id="chartdivLine"></div>

    <script language="JavaScript">
        var chart = AmCharts.makeChart("chartdivLine", {
            "type": "serial",
            "theme": "none",
            "pathToImages": "<?php echo $this->location() ?>/public/amcharts/images/",
            "dataDateFormat": "YYYY-MM-DD",
            "dataProvider": [
                <?php foreach ($this->dso as $dso) { ?>
                {
                    "date": "<?php echo $dso->DSO_YEAR ?>-<?php echo $dso->DSO_MONTH ?>-<?php print date('t',strtotime("{$dso->DSO_MONTH}/1/{$dso->DSO_YEAR}")); ?>",
                    "value": <?php echo $dso->DSO?>
                },
                <?php } ?>
            ],
            "valueAxes": [
                {
                    "axisAlpha": 0,
                    "guides": [
                        {
                            "fillAlpha": 0.1,
                            "fillColor": "#000000",
                            "inside": true,
                            "lineAlpha": 0,
                            "toValue": 20,
                            "value": 10
                        }
                    ],
                    "position": "left",
                    "showFirstLabel": false,
                    "showLastLabel": false,
                    "tickLength": 0
                }
            ],
            "graphs": [
                {
                    "balloonText": "[[category]]<br><b><span style='font-size:14px;'>value:[[value]]</span></b>",
                    "bullet": "round",
                    "dashLength": 3,
                    "valueField": "value"
                }
            ],
            "chartScrollbar": {},
            "chartCursor": {},
            "categoryField": "date",
            "categoryAxis": {
                "parseDates": true,
                "axisAlpha": 0,
                "gridAlpha": 0.1,
                "inside": true,
                "minorGridAlpha": 0.1,
                "minorGridEnabled": true
            }
        });
    </script>

<?php else: ?>
    <?php echo $this->Message($this->G("no_results_c")); ?>
<?php endif; ?>

            </div>        
            </div> 
          </div>

