<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/serial.js"></script>

<style>
    #paymentDelayForecastHistogram {
        width: 100%;
        height: 250px;
        position: relative;
        float: right;
    }
</style>

<?php if($this->allowChoice) { ?>
<form method="get">
    <select name="clientId" id="clientId">
    <option value="all"><?php $this->T("all_clients_c") ?></option>
    <?php foreach ($this->clients as $client): ?>
        <option
            value="<?php echo $client->CLIENT_ID ?>" <?php echo $this->clientId == $client->CLIENT_ID ? 'selected="selected"' : '' ?>>
            <?php echo $client->NAME ?>
        </option>
    <?php endforeach ?>
    </select>
</form>
<?php } ?>

<script type="text/javascript">
    var paymentDelayForecastHistogram = AmCharts.makeChart("paymentDelayForecastHistogram", {
        "type": "serial",
        "pathToImages": "http://www.amcharts.com/lib/3/images/",
        "categoryField": "day",
        "valueAxes": [{
            "axisAlpha": 0,
            "inside": true,
            "position": "left",
            "ignoreAxisWidth": true
        }],
        "graphs": [
            {
                "type" : "column",
                "fillAlphas": 1,
                "valueField": "value",
                "hideBulletsCount": 3
            }
        ],
        "dataDateFormat": "YYYY-MM-DD",
        "chartScrollbar": {},
        "chartCursor": {
            "categoryBalloonDateFormat": "DD-MM-YYYY",
            "cursorAlpha": 0,
            "cursorPosition": "mouse"
        },
        "categoryAxis": {
            "minPeriod": "DD",
            "parseDates": true,
            "minorGridAlpha": 0.1,
            "minorGridEnabled": true
        },
        "dataProvider": [
            <?php foreach($this->paymentForecast as $row) { ?>
            { "day" : "<?php echo $row->FORECAST_DAY ?>", "value" : <?php echo $row->FORECAST_VALUE ?> },
            <?php }?>
        ]
    });

    $(function () {
        $('#clientId').change(function () {
            $(this).parent('form').submit();
        });
    })
</script>
<table style="width: 100%;">
    <tr>
        <td class="windowPart" colspan="3">
            <span class="title"><?php $this->T("forecastHistogram_c") ?></span>
            <div id="paymentDelayForecastHistogram"></div>
        </td>
    </tr>
</table>