<?php if (count($this->realtimeSummary) > 0): ?>
    <style>
        #chartdiv, #paymentDelayForecastHistogram {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }
    </style>
    <style>
        #legenddiv {
            width: 100%;
            font-size: 11px;
            position: relative;
        }
    </style>	
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/pie.js"></script>

    <script>
        var chart = AmCharts.makeChart("chartdiv", {
            "type": "pie",
            "theme": "none",
            "colors": ["#598CB4","#C0605D","#9DB370", "#8B74A0", "#4CACBD", "#E69A5F", "#A5BBD6", "#FF0000", "#FF0000"],
            "dataProvider": [
                <?php foreach ($this->realtimeSummary as $row): ?>
                {
                    "titel": "<?php echo $row->STATE_CODE ?>",
                    "waarde": <?php echo $row->COUNTER ?>
                },
                <?php endforeach ?>
            ],
            "valueField": "waarde",
            "titleField": "titel",
        });
        var legend = new AmCharts.AmLegend();
        chart.addLegend(legend, "legenddiv");
    </script>


         <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
					<table class="table table-striped table-bordered">
					<thead>
					<tr>
						<td colspan="2"></td>
						<td colspan="4"><?php $this->T('bedragen_c') ?></td>
						<td colspan="4"><?php $this->T('betaald_c') ?></td>
					</tr>
					<tr>
						<td><?php $this->T('state_c') ?></td>
						<td><?php $this->T('files_c') ?></td>
						<td><?php $this->T('amount_c') ?></td>
						<td><?php $this->T('interest_c') ?></td>
						<td><?php $this->T('costs_c') ?></td>
						<td><?php $this->T('total_c') ?></td>
						<td><?php $this->T('amount_c') ?></td>
						<td><?php $this->T('interest_c') ?></td>
						<td><?php $this->T('costs_c') ?></td>
						<td><?php $this->T('total_c') ?></td>
					</tr>
					</thead>
					<tbody>
					<?php foreach ($this->realtimeSummary as $row): ?>
						<tr>
							<td><?php echo $row->STATE_CODE ?></td>
							<td><?php echo number_format($row->COUNTER, 0, ',', '.') ?></td>
							<td ><?php echo number_format($row->AMOUNT, 2, ',', '.') ?></td>
							<td ><?php echo number_format($row->INTEREST, 2, ',', '.') ?></td>
							<td ><?php echo number_format($row->COSTS, 2, ',', '.') ?></td>
							<td ><?php echo number_format($row->TOTAL, 2, ',', '.') ?></td>
							<td ><?php echo number_format($row->PAYED_AMOUNT, 2, ',', '.') ?></td>
							<td ><?php echo number_format($row->PAYED_INTEREST, 2, ',', '.') ?></td>
							<td ><?php echo number_format($row->PAYED_COSTS, 2, ',', '.') ?></td>
							<td ><?php echo number_format($row->PAYED_TOTAL, 2, ',', '.') ?></td>
						</tr>
					<?php endforeach ?>
					</tbody>
					<tfoot>
        <tr>
            <td><?php $this->T('Total_c') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->COUNTER, 0, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->AMOUNT, 2, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->INTEREST, 2, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->COSTS, 2, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->TOTAL, 2, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->PAYED_AMOUNT, 2, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->PAYED_INTEREST, 2, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->PAYED_COSTS, 2, ',', '.') ?></td>
            <td ><?php echo number_format($this->realtimeSummaryTotal->PAYED_TOTAL, 2, ',', '.') ?></td>
        </tr>
        </tfoot>
    </table>
                </div>                          
              </div>
            </div>  
          </div> 
<!-- Second row ends -->

        <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
    <div id="legenddiv" style="border: 2px dotted #3f3; margin: 5px 0 20px 0;"></div>
    <div id="chartdiv"></div>
              </div>
            </div>  
          </div> 
		  <?php else: ?>
    <?php echo $this->Message($this->G("no_results_c")); ?>
<?php endif; ?>

