<?php if (count($this->realtimeSummary) > 0): ?>
    <style>
        #chartdiv, #paymentDelayForecastHistogram {
            width: 100%;
            height: 400px;
            font-size: 11px;
            position: relative;
        }
    </style>
    <style>
        #legenddiv {
            width: 100%;
            font-size: 11px;
            position: relative;
        }
    </style>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
    <script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/pie.js"></script>

    <script>
        var chart = AmCharts.makeChart("chartdiv", {
            "type": "pie",
            "theme": "none",
            "dataProvider": [
                <?php foreach ($this->realtimeSummary as $row): ?>
                {
                    "titel": "<?php echo $row->STATE_CODE ?>",
                    "waarde": <?php echo $row->COUNTER ?>
                },
                <?php endforeach ?>
            ],
            "valueField": "waarde",
            "titleField": "titel",
        });
        var legend = new AmCharts.AmLegend();
        chart.addLegend(legend, "legenddiv");
    </script>




    <table class="ws_data_table" width="100%">
        <thead>
        <tr>
            <th colspan="2"></th>
            <th colspan="4"><?php $this->T('bedragen_c') ?></th>
            <th colspan="4"><?php $this->T('betaald_c') ?></th>
        </tr>
        <tr>
            <th><?php $this->T('state_c') ?></th>
            <th><?php $this->T('files_c') ?></th>
            <th><?php $this->T('amount_c') ?></th>
            <th><?php $this->T('interest_c') ?></th>
            <th><?php $this->T('costs_c') ?></th>
            <th><?php $this->T('total_c') ?></th>
            <th><?php $this->T('amount_c') ?></th>
            <th><?php $this->T('interest_c') ?></th>
            <th><?php $this->T('costs_c') ?></th>
            <th><?php $this->T('total_c') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->realtimeSummary as $row): ?>
            <tr>
                <td><?php echo $row->STATE_CODE ?></td>
                <td class="right"><?php echo number_format($row->COUNTER, 0, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->AMOUNT, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->INTEREST, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->COSTS, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->TOTAL, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->PAYED_AMOUNT, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->PAYED_INTEREST, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->PAYED_COSTS, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($row->PAYED_TOTAL, 2, ',', '.') ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
        <tfoot>
        <tr>
            <td><?php $this->T('Total_c') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->COUNTER, 0, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->AMOUNT, 2, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->INTEREST, 2, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->COSTS, 2, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->TOTAL, 2, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->PAYED_AMOUNT, 2, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->PAYED_INTEREST, 2, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->PAYED_COSTS, 2, ',', '.') ?></td>
            <td class="right"><?php echo number_format($this->realtimeSummaryTotal->PAYED_TOTAL, 2, ',', '.') ?></td>
        </tr>
        </tfoot>
    </table>
    <div id="legenddiv" style="border: 2px dotted #3f3; margin: 5px 0 20px 0;"></div>
    <div id="chartdiv"></div>
<?php else: ?>
    <?php echo $this->Message($this->G("no_results_c")); ?>
<?php endif; ?>


