<?php  echo $this->form ?>

<?php if(count($this->mails) > 0) { ?>
<table class="ws_data_table">
    <thead>
        <tr>
            <th><?php echo $this->T('mail_from_c') ?></th>
            <th><?php echo $this->T('mail_to_c') ?></th>
            <th><?php echo $this->T('creation_date_c') ?></th>
            <th><?php echo $this->T('mail_subject_c') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->mails as $mail) { ?>
        <tr>
            <td><?php echo $mail->FROM_EMAIL ?></td>
            <td><?php echo $mail->TO_EMAIL ?></td>
            <td><?php echo $mail->CREATION_DATE ?></td>
            <td><?php echo $mail->MAIL_SUBJECT ?></td>
            <td><span title="<?php $this->T("view_file_c") ?>" onclick="newscreen('<?php echo $mail->FILE_NR ?>', '<?php echo $this->pageRootUrl ?>/file-detail/view/fileId/<?php echo $mail->FILE_ID ?>')" class="ui-icon ui-icon-zoomin"></span> </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php
} else { ?>
    <div><?php echo $this->T('no_mails_found_c') ?></div>
<?php } ?>
<script type="text/javascript">
    $(function() {
        $("#TO_DATE").datepicker({dateFormat: 'dd/mm/yy'});
        $("#FROM_DATE").datepicker({dateFormat: 'dd/mm/yy'});
    });
</script>
