<?php  echo $this->form ?>

<?php if(count($this->mails) > 0) { ?>
<table class="ws_data_table" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->T('referenceclient_c') ?></th>
            <th><?php echo $this->T('debtor_c') ?></th>
            <th><?php echo $this->T('mail_from_c') ?></th>
            <th><?php echo $this->T('mail_to_c') ?></th>
            <th><?php echo $this->T('creation_date_c') ?></th>
            <th><?php echo $this->T('mail_subject_c') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->mails as $mail) { ?>
        <tr onclick="newscreen('<?php echo $mail->FILE_NR ?>', '<?php echo $this->pageRootUrl ?>/file-imported-mails/view/fileId/<?php echo $mail->FILE_ID ?>')">
            <td><?php echo $mail->REFERENCE ?></td>
            <td><?php echo $mail->CLIENT_NAME ?></td>
            <td><?php echo $mail->FROM_EMAIL ?></td>
            <td><?php echo $mail->TO_EMAIL ?></td>
            <td><?php echo $mail->CREATION_DATE ?></td>
            <td><?php echo $mail->MAIL_SUBJECT ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php
} else { ?>
    <div><?php echo $this->T('no_mails_found_c') ?></div>
<?php } ?>
<script type="text/javascript">
    $(function() {
        $("#TO_DATE").datepicker({dateFormat: 'dd/mm/yy'});
        $("#FROM_DATE").datepicker({dateFormat: 'dd/mm/yy'});
    });
</script>
