          <div class="aaa-theme-flex-row flex-content-row">
            <div class="aaa-theme-content-widget white-bg col-4 text-center">
			<div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php print $this->T("search_client_c") ?></h2></div>
              <?php echo $this->SearchBox ?>
            </div>  
          </div>

<?php if (!empty($this->results)) {  $index=0;?>		  
         <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"> <?php echo $this->totals->COUNTER ?> <?php $this->T("results_found_c") ?>
            <?php if ($this->onlyFirst) { ?>
                <?php $this->T("only_first_c", $this->onlyFirst) ?>
            <?php } ?>
			</h2></div>
                <div class="table-responsive">
                	

                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
							<td><?php $this->T("code_c"); ?></td>
							<td><?php $this->T("name_c"); ?></td>
							<td><?php $this->T("address_c"); ?></td>
							<td><?php $this->T("zipcode_c"); ?></td>
							<td><?php $this->T("city_c"); ?></td>
							<td><?php $this->T("country_c"); ?></td>
							<td><?php $this->T("files_c"); ?></td>
							<td><?php $this->T("open_files_c"); ?></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
                    </thead>
                    <tbody>
					   <?php foreach ($this->results as $row) { ?>
							<tr>
								<td><?php echo $row->CODE ?></td>
								<td><?php echo $row->NAME ?></td>
								<td><?php echo $row->ADDRESS ?></td>
								<td><?php echo $row->ZIP_CODE ?></td>
								<td><?php echo $row->CITY ?></td>
								<td><?php echo $row->COUNTRY_CODE ?></td>
								<td><?php echo $row->FILE_COUNT ?></td>
								<td><?php echo $row->OPEN_FILES ?></td>
							   <td><a class="zoom fancybox.iframe" href="<?php echo $this->location() ?>/client-detail/view/clientId/<?php echo $row->CLIENT_ID ?>"><li class="fa fa-search-plus fa-fw"></li></a></td>
							   <td><?php echo $this->Delete($this->location() . "/clients/search/hide/" . $row->CLIENT_ID, $row->NAME) ?></td>
							</tr>
						<?php $index++; } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> 
<?php } ?>
<!-- Second row ends -->

    	<script>
$(document).ready(function() {
	$(".zoom").fancybox({
		fitToView	: false,
		width		: '100%',
		height		: '100%',
		autoSize	: false,
		closeClick	: false,
		openEffect	: 'none',
		closeEffect	: 'none'
	});
});
		</script>
