<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>

         <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php echo count($this->results) ?> resultaten gevonden</h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
    <tr>
        <th><?php $this->T("Code_c"); ?></th>
        <th><?php $this->T("Dutch_c"); ?></th>
        <th><?php $this->T("French_c"); ?></th>
        <th><?php $this->T("English_c"); ?></th>
        <th><?php $this->T("country_code_c"); ?></th>
        <th></th>
        <th></th>
    </tr>				
                    </thead>
					<tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <?php $class = (empty($row->POPULATION_PLACE_ID) && $row->COUNTRY_CODE=='BE' ) ? "no-population-place" : '';?>
            <tr class="<?php echo $class ?>">
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->CITY_DUTCH ?></td>
                <td><?php echo $row->CITY_FRENCH ?></td>
                <td><?php echo $row->CITY_ENGLISH ?></td>
                <td><?php echo $row->COUNTRY_CODE ?></td>
                <td><a href="<?php echo $this->location() ?>/settings-zipcodes/edit/id/<?php echo $row->ZIP_CODE_ID ?>" ><li class="fa fa-search-plus fa-fw"></li></td>
                <td>
                    <?php echo $this->Delete($this->location()."/settings-zipcodes/view/delete/" . $row->ZIP_CODE_ID , $row->CODE) ?>
                </td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->

