<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>

         <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><?php if (count($this->results)): ?><h2 class="text-uppercase"><?php echo count($this->results) ?> resultaten gevonden</h2><?php endif; ?></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
    <tr>
        <th><?php $this->T("code_c"); ?></th>
        <th><?php $this->T("valuta"); ?></th>
        <th><?php $this->T("description_c"); ?></th>
        <th><?php $this->T("account_nr_c"); ?></th>
        <th>BIC</th>
        <th><?php $this->T("in_house_c"); ?></th>
        <th></th>
        <th></th>
    </tr>				
                    </thead>
					<tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->VALUTA ?></td>
                <td><?php echo $row->DESCRIPTION ?></td>
                <td><?php echo $row->ACCOUNT_NR ?></td>
                <td><?php echo $row->BIC ?></td>
                <td><input type="checkbox" name="inhouse" value="1" <?php echo ($row->IN_HOUSE ? 'checked="checked"' : '') ?> disabled="disabled" /></td>
                <td><a href="<?php echo $this->location() ?>/settings-accounts/edit/id/<?php echo $row->ACCOUNT_ID ?>" ><li class="fa fa-search-plus fa-fw"></li></td>
                <td>
                    <?php if($row->ACCOUNT_ID > 3): ?>
                        <?php echo $this->Delete($this->location()."/settings-accounts/view/delete/" . $row->ACCOUNT_ID , $row->CODE) ?>
                    <?php endif; ?>
                </td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->

