<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>
		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
    <tr>
        <td><?php $this->T("function_c"); ?></td>
        <td><?php $this->T("name_c"); ?></td>
        <td><?php $this->T("email_c"); ?></td>
        <td><?php $this->T("address_c"); ?></td>
        <td><?php $this->T("tel_c"); ?></td>
        <td><?php $this->T("language_c"); ?></td>
        <td></td>
        <td></td>
    </tr>
    </thead>
	<tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->FUNCTION_DESCRIPTION ?></td>
                <td><?php echo $row->NAME ?></td>
                <td><?php echo $row->EMAIL ?></td>
                <td><?php echo $row->ADDRESS ?></td>
                <td><?php echo $row->TEL ?></td>
                <td><?php echo $row->LANGUAGE?></td>
                <td><a href="<?php echo $this->location() ?>/debtor-contacts/edit/id/<?php echo $row->CONTACT_ID . "/index/".$this->index ?>" ><span title ="<?php $this->T("edit_c") ?>"  class="ui-icon ui-icon-zoomin"></span></td>
                <td><?php echo $this->Delete($this->location()."/debtor-contacts/view/delete/" . $row->CONTACT_ID . "/index/".$this->index, $row->NAME) ?></td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="8" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>