<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>

		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
						<td><?php $this->T("date_c"); ?></td>
						<td><?php $this->T("code_c"); ?></td>
						<td><?php $this->T("description_c"); ?></td>
						<td><?php $this->T("amount_c"); ?></td>
						<td><?php $this->T("invoice_c"); ?></td>
						<td><?php $this->T("invoiceable_c"); ?></td>
						<td></td>
					  </tr>
                    </thead>
                    <tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $this->Date($row->CREATION_DATE) ?></td>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->DESCRIPTION ?></td>
                <td><?php echo $this->Amount($row->AMOUNT) ?></td>
                <td><?php echo $row->INVOICE_NR ?></td>
                <td><?php echo $this->Selection($row->INVOICEABLE) ?></td>
                <td><?php echo $this->Delete($this->location()."/file-costs/view/delete/".$row->RECORD_ID."/fileId/".$this->fileId, $row->DESCRIPTION) ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="7" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
