		<!-- FACTUREN javascript code -->
		<script>
			var chart = AmCharts.makeChart("vervallen", {
				"type": "pie",
				"theme": "none",
                "colors" : ["#FF0000","#00FF00"],
				"legend": {
					"position": "right",
					"horizontalGap": 10,
					"markerSize": 10,
					"useGraphSettings": false,
					"valueWidth": 0
				},
				"dataProvider": [
					{
						"titel": "<?php echo $this->T("past_due_c") ?>",
						"waarde": <?php echo $this->totalPastDue ?>,
					},
					{
						"titel": "<?php echo $this->T("not_due_c") ?>",
						"waarde": <?php echo $this->totalNotDue ?>,
					}],
				"titleField": "titel",
				"valueField": "waarde",
				"labelText": ""
			});
		</script>
				
        <!-- REAL-TIME javascript code -->
		<script>
			var chart = AmCharts.makeChart("realtime", {
				"type": "pie",
				"theme": "none",
				"legend": {
					"position": "right",
					"horizontalGap": 10,
					"markerSize": 10,
					"useGraphSettings": false,
					"valueWidth": 0
				},
				"dataProvider": [
					<?php foreach ($this->realtimeSummary as $row): ?>
					{
						"titel": "<?php echo $row->STATE_CODE ?>",
						"waarde": <?php echo $row->COUNTER ?>
					},
					<?php endforeach ?>
				],
				"valueField": "waarde",
				"titleField": "titel",
				"labelText": ""
			});
			var legend = new AmCharts.AmLegend();
		</script>
				
        <!-- AGING javascript code -->
		<script>
			var chart = AmCharts.makeChart("aging", {
				"type": "pie",
				"theme": "none",
                "colors" : ["#00FF00","#8DFF00","#F7FF00", "#FF8C00", "#FF4600", "#FF2300", "#FF0000", "#FF0000", "#FF0000"],
				"legend": {
					"position": "right",
					"horizontalGap": 10,
					"markerSize": 10,
					"useGraphSettings": false,
					"valueWidth": 0
				},
				"dataProvider": [
					<?php foreach ($this->aging as $type => $value): ?>
					{
						"titel": "<?php echo $type ?> <?php $this->T("days_c")?>",
						"waarde": <?php echo ($value->SUM) ? $value->SUM : 0;  ?>
					},
					<?php endforeach ?>
				],
				"valueField": "waarde",
				"titleField": "titel",
				"labelText": ""
			});
			var legend = new AmCharts.AmLegend();
		</script>
        
        <!-- BETALINGSTERMIJN javascript code -->
		<script language="JavaScript">
			var gaugeChart = AmCharts.makeChart("paymentdelay", {
				"type": "gauge",
				"theme": "none",
				"axes": [
					{
						"axisThickness": 3,
						"axisAlpha": 0.5,
						"tickAlpha": 0.5,
						"valueInterval": 10,
						"bands": [
							{
								"color": "#84b761",
								"endValue": 90,
								"startValue": 0
							},
							{
								"color": "#cc4748",
								"endValue": 200,
								"innerRadius": "95%",
								"startValue": 90
							}
						],
						"bottomText": "",
						"bottomTextYOffset": 20,
						"endValue": 200
					}
				],
				"arrows": [
					{
						"value" : <?php echo $this->paymentDelay; ?>
					}
				]
			});
		</script>
        
		<script type="text/javascript">
			var paymentDelayForecastHistogram = AmCharts.makeChart("paymentDelayForecastHistogram", {
				"type": "serial",
				"pathToImages": "http://www.amcharts.com/lib/3/images/",
				"categoryField": "day",
				"valueAxes": [{
					"axisAlpha": 0,
					"inside": true,
					"position": "left",
					"ignoreAxisWidth": true
				}],
				"graphs": [
					{
						"type" : "column",
						"fillAlphas": 1,
						"valueField": "value",
						"hideBulletsCount": 3
					}
				],
				"dataDateFormat": "YYYY-MM-DD",
				"chartScrollbar": {},
				"chartCursor": {
					"categoryBalloonDateFormat": "DD-MM-YYYY",
					"cursorAlpha": 0,
					"cursorPosition": "mouse"
				},
				"categoryAxis": {
					"minPeriod": "DD",
					"parseDates": true,
					"minorGridAlpha": 0.1,
					"minorGridEnabled": true
				},
				"dataProvider": [
					<?php foreach($this->paymentForecast as $row) { ?>
					{ "day" : "<?php echo $row->FORECAST_DAY ?>", "value" : <?php echo $row->FORECAST_VALUE ?> },
					<?php }?>
				]
			});
		</script>
		<script>
		$(document).ready(function(){
   		$('tr.agenda').bind('click', function(){

        var record_id   = $(this).attr('id');
		var link        = '<?php echo $this->location() ?>/files/search/agenda/' + record_id;
        $.fancybox({
            'width'             : '100%',
            'height'            : '100%',
            'autoScale'         : false,
            'transitionIn'      : 'none',
            'transitionOut'     : 'none',
            'type'              : 'iframe',
            'href'              : link
				});
			});
		});
		</script>
    	<script>
		$(document).ready(function(){
   		$('tr.dashboard').bind('click', function(){

        var record_id   = $(this).attr('id');
		
		switch(record_id) {
			 case "1":
				var link        = '<?php echo $this->location() ?>/print/documents'
				break;
			 case "2":
				var link        = '<?php echo $this->location() ?>/payments/search'
				break;
			 case "3":
				 var link        = '<?php echo $this->location() ?>/imported-mail/overview'
			 case "4":
				 var link        = '<?php echo $this->location() ?>/disputes/search'
		 }
		
        $.fancybox({
            'width'             : '100%',
            'height'            : '100%',
            'autoScale'         : false,
            'transitionIn'      : 'none',
            'transitionOut'     : 'none',
            'type'              : 'iframe',
            'href'              : link
				});
			});
		});
		</script>

        <style>
            .slice1 .amcharts-pie-slice {
                fill: #000;
            }
        </style>
	

          <div class="aaa-theme-flex-row flex-content-row">
            <div class="aaa-theme-content-widget white-bg col-1 text-center">
			<div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><a href="<?php echo $this->Location() ?>/invoices/search"><?php $this->T("invoices_c") ?></a></h2></div>
              <div id="vervallen" class="aaa-theme-chart"></div>	
            </div>
            <div class="aaa-theme-content-widget white-bg col-1 text-center">
              <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><a href="<?php echo $this->Location() ?>/report/realtime"><?php $this->T("menu_report_realtime") ?></a></h2></div>
              <div id="realtime" class="aaa-theme-chart"></div>
            </div>
            <div class="aaa-theme-content-widget white-bg col-1 text-center">
              <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><a href="<?php echo $this->Location() ?>/report/aging"><?php $this->T("menu_report_aging") ?></a></h2></div>
              <div id="aging" class="aaa-theme-chart"></div>
            </div>
          </div>
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase">Dashboard Overview</h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("description_c"); ?></td>
                        <td><?php $this->T("number_c"); ?></td>
                      </tr>
                    </thead>
                    <tbody>
                      <tr style="cursor: pointer" <?php echo $this->onclick("{$this->location()}/print/documents"); ?>>
                        <td><?php $this->T("documents_to_be_printed_c") ?></td>
                        <td><?php echo $this->toBePrinted?></td>
                      </tr>
                      <tr style="cursor: pointer" <?php echo $this->onclick("{$this->location()}/payments/search"); ?>>
                        <td><?php $this->T("Total_payments_c") ?> <?php $this->T("vandaag_c") ?></td>
                        <td><?php echo $this->amount($this->payedToday)?></td>
                      </tr>
                      <!--
                      <tr style="cursor: pointer" <?php echo $this->onclick("{$this->location()}/imported-mail/overview"); ?>>
                        <td>E-mails <?php $this->T("vandaag_c") ?></td>
                        <td><?php echo $this->emailsToday?></td>
                      </tr>
                      -->
                      <tr style="cursor: pointer" <?php echo $this->onclick("{$this->location()}/disputes/search"); ?>>
                        <td><?php $this->T("disputes_today_c") ?></td>
                        <td><?php echo $this->disputesToday?></td>
                      </tr>                   
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
            <div class="col-1">              
              <div class="aaa-theme-content-widget white-bg col-1 text-center">
              <h2 class="text-uppercase"><?php echo $this->T("gem_betalingstermijn_c") ?></h2>
              <div id="paymentdelay" class="aaa-theme-chart"></div>	
            </div>        
            </div> 
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("agenda_c") ?></h2></div>
                <div class="table-responsive">
				<?php if (!empty($this->agenda)) { ?>
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("description_c"); ?></td>
                        <td><?php $this->T("number_c"); ?></td>
                      </tr>
                    </thead>
                    <tbody>
					<?php foreach ($this->agenda as $agenda) {  ?>
                      <tr  style="cursor: pointer" <?php echo $this->onclick("{$this->location()}/files/search/agenda/{$agenda->STATE_ID}"); ?>>
                        <td><?php echo $agenda->STATE_DESCRIPTION ?></td>
                        <td><?php echo $agenda->COUNTER?></td>
                      </tr>
                    <?php } ?>                 
                    </tbody>
                  </table> 
				<?php } ?>
                </div>                          
              </div>
            </div>         
          </div> <!-- Second row ends -->
