<script>
    $(document).ready(function(){
        $('tr.dossier').bind('click', function(){

            var record_id   = $(this).attr('id');

            var link        = '<?php echo $this->pageRootUrl ?>/file-invoices/view/fileId/' + record_id;

            $.fancybox({
                'width'             : '100%',
                'height'            : '100%',
                'autoScale'         : false,
                'transitionIn'      : 'none',
                'transitionOut'     : 'none',
                'type'              : 'iframe',
                'href'              : link
            });
        });
    });
</script>

<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("invoice_c"); ?> / <?php $this->T("police"); ?></td>
						<td><?php $this->T("factuurdatum_c"); ?></td>
						<td><?php $this->T("start_date_c"); ?></td>
						<td><?php $this->T("amount_c"); ?></td>
						<td><?php $this->T("saldo_c"); ?></td>
						<td><?php $this->T("dispute_c"); ?></td>
						<td><?php $this->T("state_c"); ?></td>
						<td><?php $this->T("train_type_c"); ?></td>
						<td></td>
                      </tr>
                    </thead>
                    <tbody>
<?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) {
          
            ?>
                <tr class="dossier" style="cursor: pointer" id="<?php echo $row->FILE_ID ?>">
                <td><?php echo $row->INVOICE_DOCCODE."/".$row->REFERENCE."/".$row->INVOICE_DOCLINENUM ?>
                   <br><?php if (!empty($row->CONTRACT_NUMBER)) { ?><?php echo $row->CONTRACT_NUMBER?> : <?php echo $row->CONTRACT_INSURED?><br><?php } ?>
                   <?php echo $this->Date($row->INVOICE_FROMDATE) ?> -> <?php echo $this->Date($row->INVOICE_TODATE) ?>
                   </td>
                <td><?php echo $this->Date($row->INVOICE_DATE) ?></td>
                <td><?php echo $this->Date($row->START_DATE) ?></td>
                <td align="right"><?php echo $this->Amount($row->AMOUNT) ?> <?php echo $row->VALUTA?></td>
                <td align="right"><?php echo $this->Amount($row->SALDO) ?> <?php echo $row->VALUTA?></td>
                <td align="center"><?php echo $this->GoodBad(!$row->DISPUTE) ?></td>
                <td><?php echo $row->STATE_CODE ?></td>
                <td><?php echo $row->TRAIN_TYPE ?></td>
                <td><?php if (!empty($this->manageInvoices)) { ?><a href="<?php echo $this->location() ?>/file-invoices/edit/id/<?php echo $row->REFERENCE_ID ?>/fileId/<?php echo $this->fileId ?>" ><li class="fa fa-pencil fa-fw"></li></a<?php } ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="11" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>                 
                    </tbody>
                  </table>    
                </div>                          
              </div>

		  
