<div class="aaa-theme-content-widget aaa-theme-login-widget white-bg">
			<header class="text-center">
	          <img src="<?php echo $this->location() ?>/public/images/logo.jpg" class="img-responsive">
	        </header>
	        <form action="<?php echo $this->url() ?>" class="aaa-theme-login-form"  method="post">
	        	<div class="form-group">
	        		<div class="input-group">
		        		<div class="input-group-addon"><i class="fa fa-user fa-fw"></i></div>	        		
		              	<?php echo $this->loginForm->username ?>           
		          	</div>	
	        	</div>
	        	<div class="form-group">
	        		<div class="input-group">
		        		<div class="input-group-addon"><i class="fa fa-key fa-fw"></i></div>	        		
		              	<?php echo $this->loginForm->password ?>          
		          	</div>	
	        	</div>
				<div class="form-group">
					<?php echo $this->loginForm->submit ?>
				</div>
	        </form>
    <?php if ($this->showError) {
        print "<br>".$this->Error($this->G('incorrect_login_c'));
    } ?>

</div>
        <!--
		<div class="aaa-theme-content-widget aaa-theme-login-widget aaa-theme-register-widget white-bg">
			<p>Nog geen gebruiker? <strong><a href="http://www.aaa.be/nl-BE/CM-Solutions/CM-Software" class="orange-text">Start nu!</a></strong></p>
		</div>
		-->
