<script type="text/javascript" src="<?php echo $this->location() ?>/public/js/jquery.raty.js"></script>
<script type="text/javascript">
    $(function() {
        $('[data-rater]').each(function () {
            $(this).raty({'score': $(this).attr('data-rater'), 'scoreName' : 'DEBTOR_SCORE' });
        });
    })
</script>
          <div class="aaa-theme-flex-row flex-content-row">
          <div class="col-1">

            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("debtor_c") ?></h2></div>
                <div class="table-responsive">
				<table class="table">
                  <tbody>
                    <tr><td>
                <?php
                if ($this->generalFormSaved) {
                    print $this->Ok($this->G("saved_c"));
                }
                ?>
                <?php
                if ($this->debtorInvited) {
                    print $this->Ok($this->G("debtor_invited_c"));
                }
                ?>
                <?php
                if ($this->generalFormError) {
                    print $this->Error($this->G("not_all_fields_c"));
                }
                ?>
                <?php
                if ($this->generalPassError) {
                    print $this->Error($this->G("confirm_pass_c"));
                }
                ?>
                <?php
                if ($this->subdebtorInvalid) {
                    print $this->Error($this->G("subdebtor_invalid_c"));
                }
                ?>

                <form enctype="application/x-www-form-urlencoded" action="" method="post">
                    <?php print $this->generalForm->NAME ?>
                    <?php $this->T("debtor_score_c") ?>
                    <div data-rater="<?php echo $this->currentRating ?>"></div>
                    <?php print $this->generalForm->VATNR ?>
                    <?php print $this->generalForm->SUPER_DEBTOR_NAME ?>
                    <?php print $this->generalForm->SUPER_DEBTOR_ID ?>
                    <?php print $this->generalForm->ADDRESS ?>
                    <?php print $this->generalForm->COUNTRY_ID ?>
                    <?php print $this->generalForm->ZIP_CODE ?>
                    <?php print $this->generalForm->CITY ?>
                    <?php print $this->generalForm->BIRTH_DAY ?>
                    <?php print $this->generalForm->E_MAIL ?>
                    <?php print $this->generalForm->TELEPHONE ?>
                    <?php print $this->generalForm->TELEFAX ?>
                    <?php print $this->generalForm->GSM ?>
                    <?php print $this->generalForm->LANGUAGE_ID ?>
                    <?php print $this->generalForm->EXTRA_FIELD ?>
                    <?php print $this->generalForm->TRAIN_TYPE ?>
                    <?php print $this->generalForm->DEBTOR_ID ?>
                    <?php print $this->generalForm->debtor_id ?>
                    <?php print $this->generalForm->submit ?>
                </form>
                <script>
                    $(function () {
                        $("#BIRTH_DAY").datepicker({dateFormat: 'dd/mm/yy'});
                    });
                </script>
              </td></tr></tbody></table></div>
              </div>
            </div>
			
			<div class="col-1">
			 <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("info_c") ?></h2></div>
                <div class="table-responsive">
				<table class="table">
                  <tbody>
                    <tr><td>

                <dd>&nbsp;</dd>
                <dt><?php $this->T("Created_c") ?> </dt>
                <dd><?php echo $this->date($this->debtor->CREATION_DATE) ?></dd>
                <dt><?php $this->T("gem_betalingstermijn_c") ?></dt>
                <?php if($this->nrOfPayments > 0) { ?>
                    <dd><?php echo $this->paymentDelay ?> (<?php $this->T("based_on_payments_c") ?>: <?php echo $this->nrOfPayments ?>)</dd>
                <?php } else { ?>
                    <dd><?php echo $this->T("insufficient_data_for_delay_c") ?></dd>
                <?php } ?>
                <br><br>
                <?php if ($this->report && !empty($this->report->financial_data->fiscal_year)) {  ?>
                <span class="title"><?php echo $this->T('credit_ratios_c'); ?></span>
                <dd>&nbsp;</dd>
                <table class="dataTable">
                    <tr>
                        <th><?php echo $this->T('credit_nrs_and_ratios') ?></th>
                        <th align="right"><?php echo (string) $this->report->financial_data->fiscal_year['year'] ?></th>
                    </tr>
                    <?php if (!empty($this->ratios)) { foreach ($this->ratios as $ratio) {  $ratio = $this->report->financial_data->fiscal_year->$ratio;?>
                        <tr>
                            <th><?php echo (string) $ratio['label'] ?></th>
                            <td align="right"> <?php  if ($ratio['settings-currency'] == 'EUR') { ?> <?php   echo $this->amount((string) $ratio['amount']) ?> <?php } else { ?>
                            <?php  ?> <?php   echo (string) $ratio['amount']; ?> <?php  } ?></td>
                        </tr>
                    <?php } ?>
                    <?php } ?>
                </table>
                <?php } ?>

                 </td></tr></tbody></table>         </div>
              </div>
            </div>
			
			
            <?php if ($this->report) {
                $maxIndex = sizeof($this->report->credit_advice->delay_payment_risk->risk)-1;
                $riskIndex = (int) $this->report->credit_advice->delay_payment_risk->risk[$maxIndex]->risk_index;
            ?>
			<div class="col-1">
            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("general_c") ?></h2></div>
                <div class="table-responsive">
				<table class="table">
                  <tbody>
                    <tr><td>
					

                <dd>&nbsp;</dd>
                <dt><label><?php $this->T("address_c") ?></label></dt>
                <dd><?php echo (string) $this->report->descriptive->name; ?><br>
                    <?php echo (string) $this->report->descriptive->address->raw_street; ?>
                    <br><?php echo (string) $this->report->descriptive->address->zip; ?> <?php echo (string) $this->report->descriptive->address->locality; ?>
                    <br><?php echo (string) $this->report->descriptive->address->country; ?>
                    <br><?php echo (string) $this->report->descriptive->national_identification; ?>
                </dd>
                <dd>&nbsp;</dd>
                <span class="title"><?php $this->T("credit_rating_c") ?></span>
                <dd>&nbsp;</dd>
                <dt><label><?php $this->T("credit_score_c") ?></label></dt>
                <dd><?php echo (string) $this->report->credit_advice->score ?>/<?php echo (string) $this->report->credit_advice->score_scale ?></dd>
                <dt><label><?php $this->T("credit_limit_c") ?></label></dt>
                <dd><?php echo $this->amount((string) $this->report->credit_advice->credit_opinion) ?></dd>
                <dt><label><?php echo (string) $this->report->credit_advice->type_of_risks['label']; ?></label></dt>
                <dd><?php echo (string) $this->report->credit_advice->type_of_risks->risk[$riskIndex]; ?></dd>
                <br>
                <span class="title"><?php echo $this->T('credit_incident_overview_c'); ?></span>
                <dd>&nbsp;</dd>
                <?php if (!empty($this->report->incidents->incident)) { ?>
                    <?php foreach ($this->report->incidents->incident as $incident) { ?>
                        <br></bre><b><?php echo $this->date((string) $incident->date) ?> : <?php echo (string) $incident->type ?></b>
                        <?php if (!empty($incident->jurisdiction)) { ?> <br><?php echo (string) $incident->jurisdiction; ?> <?php } ?>
                    <?php } ?>
                <?php } else { ?>
                <?php echo $this->Message($this->G("no_credit_incidents_found_c")); ?>
                <?php } ?>
                <br><br>
                <span class="title"><?php echo $this->T('download_report_c'); ?></span>
                <br>(<?php echo $this->T('aantal_eenheden_c'); ?> : <?php echo $this->binfo_counter ?>)
                <br><a href="<?php echo $this->location() ?>/binfo/binfo/vat/<?php echo $this->vat ?>">
                    <span title="<?php $this->T("view_c") ?>" class="ui-icon ui-icon-disk"></span></a>
                <br><br><i><?php $this->T("gegevens_by_eurodb_c") ?></i>

                 </td></tr></tbody></table>                 </div>
              </div>
            </div>
            <?php } ?>

</div>
<script type="text/javascript">
$(function () {
    var cache = {}, lastXhr;
    $("#SUPER_DEBTOR_NAME").autocomplete({
        minLength: 3,
        autoFocus: true,
        source: function (request, response) {
            var term = request.term;
            if (term in cache) {
                response(cache[ term ]);
                return;
            }
            lastXhr = $.getJSON("<?php echo $this->Location() ?>/ajax/debtors", request, function (data, status, xhr) {
                cache[ term ] = data;
                if (xhr === lastXhr) {
                    response(data);
                }
            });
        },
        select: function (evt, ui) {
            var CurrentValue = ui.item.value;
            var ArrayValues = CurrentValue.split("|");
            $('#SUPER_DEBTOR_NAME').val(ArrayValues[0]);
            $('#SUPER_DEBTOR_ID').val(ArrayValues[11]);
            response(ArrayValues[0]);
        }, minLength: 2
    });
});
</script>
