
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"> <?php echo $this->T("documents_to_be_printed_c") ?></h2></div>
                <div class="table-responsive">
                	

                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("collector_c"); ?></td>
                        <td><?php $this->T("description_c"); ?></td>
                        <td><?php $this->T("number_c"); ?></td>
                        <td></td>
                        <td></td>
                      </tr>
                    </thead>
                    <tbody>
					<?php if (!empty($this->toBePrinted)) { ?>
					<?php foreach ($this->toBePrinted as $template) { ?>
						<tr>
							<td><?php echo $template->COLLECTOR_NAME ?></td>
							<td><?php echo $template->DESCRIPTION ?></td>
							<td><?php echo $template->COUNTER ?></td>
							<td><a href="<?php echo $this->location() ?>/print/to-be-printed/templateId/<?php echo $template->TEMPLATE_ID ?>/collectorId/<?php echo $template->COLLECTOR_ID ?>"
               target="_blank"><li class="fa fa-floppy-o fa-fw"></li></td>
							<td><?php echo $this->Delete($this->location() . "/print/documents/setPrinted/1/templateId/" . $template->TEMPLATE_ID . "/collectorId/".$template->COLLECTOR_ID, $template->DESCRIPTION) ?></td>
						</tr>
						<?php } } else { ?>
							<tr>
								<td colspan="7" class="no_results">
									<?php $this->T("no_results_c"); ?>
								</td>
							</tr>
						<?php } ?>
                    </tbody>
                   </table>    
                </div>                          
              </div>
            </div>  
          </div> 
<!-- Second row ends -->