<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>
<h3><?php echo count($this->results) ?> resultaten gevonden</h3>
<form method="get">
    <label for="searchInput" class="label">Search</label> <input type="text" id="searchInput" class="field" value="<?php echo $this->search?>" name="zoeken" size="25"> <input type="submit" value="search" name="submit" class="submit">
</form>
<table id="data" class="tablesorter ws_data_table" width="100%">
    <thead>
    <tr>
        <th>nav</th>
        <th><?php $this->T("Code_c"); ?></th>
        <th>NL</th>
        <th>FR</th>
        <th>EN</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->NAV ?></td>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->NL ?></td>
                <td><?php echo $row->FR ?></td>
                <td><?php echo $row->EN ?></td>
                <td><a href="<?php echo $this->location() ?>/settings-texts/edit/id/<?php echo $row->TEKSTEN_ID ?>" ><span title ="<?php $this->T("edit_c") ?>"  class="ui-icon ui-icon-zoomin"></span></td>
                <td>
                    <?php $authNamespace = new Zend_Session_Namespace('Zend_Auth'); ?>
                    <?php if ($authNamespace->online_user == 'ADMIN'): ?>
                        <?php echo $this->Delete($this->location()."/settings-texts/view/delete/" . $row->TEKSTEN_ID , $row->CODE) ?>
                    <?php endif; ?>
                </td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</table>
