<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>
<div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg aaa-theme-overflow-hidden">
			  <form method="get">
    <label for="searchInput" class="label">Search</label> <input type="text" id="searchInput" class="field" value="<?php echo $this->search?>" name="zoeken" size="25"><br><input type="submit" value="<?php echo $this->T('search_c') ?>" name="submit" class="submit">
</form>
			  </div>
			  </div>
			</div>

         <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><?php if (count($this->results)): ?><h2 class="text-uppercase"><?php echo count($this->results) ?> <?php echo $this->T('results_found_c') ?></h2><?php endif ?></div>
                <div class="table-responsive">
				
                  <table class="table table-striped table-bordered">
                    <thead>
    <tr>
        <th>nav</th>
        <th><?php $this->T("Code_c"); ?></th>
        <th>NL</th>
        <th>FR</th>
        <th>EN</th>
        <th></th>
        <th></th>
    </tr>			
                    </thead>
					<tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->NAV ?></td>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->NL ?></td>
                <td><?php echo $row->FR ?></td>
                <td><?php echo $row->EN ?></td>
                <td><a href="<?php echo $this->location() ?>/settings-texts/edit/id/<?php echo $row->TEKSTEN_ID ?>" ><li class="fa fa-search-plus fa-fw"></li></td>
                <td>
                    <?php $authNamespace = new Zend_Session_Namespace('Zend_Auth'); ?>
                    <?php if ($authNamespace->online_user == 'ADMIN'): ?>
                        <?php echo $this->Delete($this->location()."/settings-texts/view/delete/" . $row->TEKSTEN_ID , $row->CODE) ?>
                    <?php endif; ?>
                </td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>				

                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->
