		<script>
		$(document).ready(function(){
   		$('tr.dossier').bind('click', function(){

        var record_id   = $(this).attr('id');
		var record_id2	= $(this).attr('id2');

        var link        = '<?php echo $this->location() ?>/file-invoices/edit/id/' + record_id + '/fileId/' + record_id2;
		
        $.fancybox({
            'width'             : '100%',
            'height'            : '100%',
            'autoScale'         : false,
            'transitionIn'      : 'none',
            'transitionOut'     : 'none',
            'type'              : 'iframe',
            'href'              : link
				});
			});
		});
		</script>

          <div class="aaa-theme-flex-row flex-content-row">
            <div class="aaa-theme-content-widget white-bg col-1 text-center">
              <h2 class="text-uppercase"><?php print $this->T('search_disputed_invoices_c') ?></h2>
              <form class="aaa-theme-login-form" method="post">
              <div class="row form-group">				
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->DEBTOR_NAME ?>
				</div>
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->FILE_REFERENCE ?>
                </div> 
              </div>
              <div class="row form-group">
                <div class="col-lg-6 col-md-6 form-group">
                    <label></label>
                    <?php print $this->form->DISPUTE_STATUS ?>
				</div>
                <div class="col-lg-6 col-md-6 form-group">
                    <label></label>
                    <?php print $this->form->DISPUTE_ASSIGNEE ?>
                </div>
              </div>
              <div class="row form-group">
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->DATE_STARTED_FROM ?>                  
                </div>
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->DATE_STARTED_TILL ?>                   
                </div>			
              </div>
              <div class="row form-group">
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->DATE_ENDED_FROM ?>                 
                </div>
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->DATE_ENDED_TILL ?>                  
                </div>                  
              </div>
              <div class="row form-group">
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->EXPIRY_DATE_FROM ?>                 
                </div> 
                <div class="col-lg-6 col-md-6 form-group">                  
                    <label></label>
                    <?php print $this->form->EXPIRY_DATE_TILL ?>              
                </div> 
              </div>
			  <div class="row form-group">
                <div class="col-lg-6 col-md-6 form-group">                  
                    <?php print $this->form->submit ?>          
                </div>                  
              </div>                       
            </form>
            </div>	
		</div>

		<?php if(count($this->disputedInvoices) > 0) { ?>
		
		 <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase">&nbsp; </h2></div>
                <div class="table-responsive">
				  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
						<td><?php $this->T('invoice_number_c') ?></td>
						<td><?php $this->T('relationCode_c') ?></td>
						<td><?php $this->T('debtor_c') ?></td>
						<td><?php $this->T('dispute_status_c') ?></td>
						<td><?php $this->T('dispute_assignee_c') ?></td>
						<td><?php $this->T('debtor_dispute_email_c') ?></td>
						<td><?php $this->T('debtor_dispute_phone_c') ?></td>
						<td><?php $this->T('dispute_amount_c') ?></td>
						<td><?php $this->T('debtor_dispute_comment_c') ?></td>
                      </tr>
                    </thead>
                    <tbody>
					<?php foreach($this->disputedInvoices as $dispute) { ?>
					<tr class="dossier" style="cursor: pointer" id="<?php echo $dispute->REFERENCE_ID ?>" id2="<?php echo $dispute->FILE_ID ?>">
						<td><?php print $dispute->REFERENCE ?></td>
						<td><?php print $dispute->DEBTOR_NUMBER ?></td>
						<td><?php print $dispute->DEBTOR_NAME ?></td>
						<td><?php print $dispute->DISPUTE_STATUS ?></td>
						<td><?php print $dispute->DISPUTE_ASSIGNEE ?></td>
						<td><?php print $dispute->DEBTOR_DISPUTE_EMAIL ?></td>
						<td><?php print $dispute->DEBTOR_DISPUTE_PHONE ?></td>
						<td><?php print $dispute->DISPUTE_AMOUNT ?></td>
						<td><?php print $dispute->DEBTOR_DISPUTE_COMMENT ?></td>
					</tr>
					<?php } ?>
					</tbody>
                  
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> 
<?php } else { ?>
        <p><?php //print $this->T("no_disputed_invoices_found_c") ?></p>
<?php }?>

<script type="text/javascript">
    $('[data-fieldtype=datepicker]').datepicker({dateFormat: 'dd/mm/yy'});
</script>
<!-- Second row ends -->	
