<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>

          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                
                <div class="table-responsive">
                	

                  <table class="table table-striped table-bordered">
                    <thead>
						<tr>
							<td><?php $this->T("function_c"); ?></td>
							<td><?php $this->T("name_c"); ?></td>
							<td><?php $this->T("email_c"); ?></td>
							<td><?php $this->T("tel_c"); ?></td>
							<td><?php $this->T("language_c"); ?></td>
							<td></td>
							<td></td>
						</tr>
                    </thead>
                    <tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->FUNCTION_DESCRIPTION ?></td>
                <td><?php echo $row->NAME ?></td>
                <td><?php echo $row->EMAIL ?></td>
                <td><?php echo $row->TEL ?></td>
                <td><?php echo $row->LANGUAGE?></td>
                <td><a href="<?php echo $this->location() ?>/client-contacts/edit/id/<?php echo $row->CONTACT_ID . "/index/".$this->index ?>" ><li class="fa fa-search-plus fa-fw"></li></td>
                <td><?php echo $this->Delete($this->location()."/client-contacts/view/delete/" . $row->CONTACT_ID . "/index/".$this->index, $row->NAME) ?></td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="8" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</script>
                  </tbody></table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->

