


				  <div class="aaa-theme-flex-row flex-content-row aaa-theme-overflow-hidden"> <!-- overflow hidden for iPad mini landscape view-->
					<div class="col-1">              
					  <div class="aaa-theme-content-widget white-bg col-1">

    <?php if($this->success) { ?>
        <div><?php print $this->Ok('Het bestand werd correct ingelezen.') ?></div>
    <?php } ?>
    <?php
    foreach($this->messages as $message) {
        ?>
        <div><?php print $this->error($message) ?></div>
    <?php
    }
    foreach($this->warnings as $warning) {
        ?>
        <div><?php print $this->warning($warning) ?></div>
    <?php
    }
    ?>

<?php print $this->form ?>
					  
					</div>        
					</div> 
				  </div>


				  <div class="aaa-theme-flex-row flex-content-row aaa-theme-overflow-hidden"> <!-- overflow hidden for iPad mini landscape view-->
					<div class="col-1">              
					  <div class="aaa-theme-content-widget white-bg col-1">

<?php print $this->explanation ?>
					  
					</div>        
					</div> 
				  </div>

