<script>
    $(document).ready(function(){
        $('td.list').bind('click', function(){

            var record_id   = $(this).attr('id');
            var link        = '<?php echo $this->location() ?>/file-actions/view/fileId/' + record_id;

            $.fancybox({
                'width'             : '100%',
                'height'            : '100%',
                'autoScale'         : false,
                'transitionIn'      : 'none',
                'transitionOut'     : 'none',
                'type'              : 'iframe',
                'href'              : link
            });
        });
    });
</script>


<div class="aaa-theme-flex-row flex-content-row">
    <div class="aaa-theme-content-widget white-bg col-1 text-center">
        <?php echo $this->searchForm; ?>
    </div>
</div>
<div class="aaa-theme-flex-row flex-content-row">
    <div class="col-1">
        <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
            <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T('total_c') ?>: <?php echo count($this->results); ?></h2></div>
            <div class="table-responsive">
                <form enctype="application/x-www-form-urlencoded" method="post" action="">
                <dl class="zend_form">

                    <?php if ($this->results) { ?><input type="checkbox" id="checkAll"><?php echo $this->T("check_all_c")?>  <?php } ?>


                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <td><?php $this->T("reference_c"); ?></td>
                        <td><?php $this->T("action_date_c"); ?></td>
                        <td><?php $this->T("created_c"); ?></td>
                        <td><?php $this->T("code_c"); ?></td>
                        <td><?php $this->T("via_c"); ?></td>
                        <td><?php $this->T("description_c"); ?></td>
                        <td><?php $this->T("remarks_c"); ?></td>
                        <td><?php $this->T("user_c"); ?></td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->results as $row): ?>
                        <tr>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $row->REFERENCE ?></td>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $this->Date($row->ACTION_DATE) ?></td>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $this->Date($row->CREATION_DATE) ?></td>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $row->ACTION_CODE ?></td>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $row->VIA ?></td>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $row->ACTION_DESCRIPTION ?></td>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $row->REMARKS ?></td>
                            <td class="list" id="<?php echo $row->FILE_ID ?>" ><?php echo $row->CREATION_USER ?></td>
                            <td><input type = checkbox name="confirmSelection[]" value="<?php echo $row->FILE_AGENDA_ID ?>"></td>
                        </tr>
                    <?php endforeach; ?>

                    <script>
                        $(function() {
                            $("#STARTDATE").datepicker({dateFormat: 'dd/mm/yy'});
                        });
                        $(function() {
                            $("#ENDDATE").datepicker({dateFormat: 'dd/mm/yy'});
                        });

                        $("#checkAll").click(function () {
                            $('input:checkbox').not(this).prop('checked', this.checked);
                        });
                    </script>
                </table>
                    <dt id="submit-label">&#160;</dt><dd id="submit-element">
                        <input type="submit" name="submit" id="submit" value="<?php echo $this->T("confirm_actions_c")?>"></dd>
                </dl>
                </form>
            </div>
        </div>
    </div>
</div> <!-- Second row ends -->

