         <div class="aaa-theme-flex-row flex-content-row">
          <div class="col-1">

            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("document_toevoegen_c") ?></h2></div>


<?php
if ($this->formSaved) {
    print $this->Ok($this->G("saved_c"));
}
?>
<?php
if ($this->formError) {
    print $this->Error($this->G("not_all_fields_c"));
}
?>

<?php print $this->form ?>
</div>
</div>
</div>
</div>