<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>


		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
						<td><?php $this->T("filename_c"); ?></td>
						<td><?php $this->T("visible_c"); ?></td>
						<td><?php $this->T("invoice_c"); ?></td>
						<td><?php $this->T("date_c"); ?></td>
						<td><?php $this->T("user_c"); ?></td>
						<td></td>
						<td></td>
						<td></td>
					  </tr>
                    </thead>
                    <tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->DESCRIPTION ?></td>
                <td><?php echo $this->Selection($row->VISIBLE) ?></td>
                <td><?php echo $row->REFERENCE ?></td>
                <td><?php echo $row->CREATED ?></td>
                <td><?php echo $row->CREATEDBY ?></td>
                <td><a href="<?php echo $this->location() ?>/downloader/document/id/<?php echo $row->FILE_DOCUMENTS_ID ?>/verify/<?php echo sha1("{$row->FILE_DOCUMENTS_ID}Triple@"); ?>"><li class="fa fa-floppy-o fa-fw"></li></a></td>
                <td>
                    <a href="<?php echo $this->location() ?>/file-documents/edit/fileDocumentId/<?php echo $row->FILE_DOCUMENTS_ID ?>/fileId/<?php echo $this->fileId ?>" ><li class="fa fa-pencil fa-fw"></li></a>
                </td>
                <td><?php if ($this->online_user == $row->CREATEDBY or isset($this->MayDelete)) { echo $this->Delete($this->location()."/file-documents/view/delete/".$row->FILE_DOCUMENTS_ID."/fileId/".$this->fileId, $row->DESCRIPTION); } ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="9" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>

