<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>
<?php
if ($this->added) {
    print $this->Ok($this->G("saved_c"));
}
if ($this->pdf > 0) { ?>
<script language="javascript">
    newscreen('', '<?php echo $this->location() ?>/print/template/fileActionId/<?php echo $this->pdf ?>');
    </script>
<?php } ?>


		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
						<td><?php $this->T("action_date_c"); ?></td>
						<td><?php $this->T("code_c"); ?></td>
						<td><?php $this->T("via_c"); ?></td>
						<td><?php $this->T("description_c"); ?></td>
						<td><?php $this->T("remarks_c"); ?></td>
						<td><?php $this->T("user_c"); ?></td>
						<td></td>
						<td></td>
                      </tr>
                    </thead>
                    <tbody>
 <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <?php  if ($row->PRINTED == 'Y') $class="class='printed'"; else {
                $class = "";
            } ?>
            <tr <?php echo $class; ?>>
                <td><?php echo $this->Date($row->ACTION_DATE) ?></td>
                <td><?php echo $row->ACTION_CODE ?></td>
                <td><?php echo $row->VIA ?></td>
                <td><?php echo $row->ACTION_DESCRIPTION ?></td>
                <td><?php echo $row->REMARKS ?></td>
                <td><?php echo $row->ACTION_USER ?></td>
                <td><?php if (!empty($row->TEMPLATE_CONTENT) && $this->viewActionContent) { ?>
                    <a href="<?php echo $this->location() ?>/print/template/fileActionId/<?php echo $row->FILE_ACTION_ID ?>"
                       target="_blank"><li class="fa fa-floppy-o fa-fw"></li></a>
                        <?php } ?>
                </td>
                <td><?php if (!empty($this->mayDelete)) { echo $this->Delete($this->location() . "/file-actions/view/delete/" . $row->FILE_ACTION_ID . "/fileId/" . $this->fileId, $row->ACTION_DESCRIPTION); } ?></td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="7" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>                
                    </tbody>
                  </table>    
                </div>                          
              </div>


