         <div class="aaa-theme-flex-row flex-content-row">
          <div class="col-1">

            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("add_ref_c") ?></h2></div>
<?php
if ($this->formSaved) {
    print $this->Ok($this->G("saved_c"));
}
?>
<?php
if ($this->formError) {
    print $this->Error($this->G("not_all_fields_c"));
}
?>

<?php print $this->form ?>


<script language="javascript">
    function autoCalculate() {
        var value = $('#AUTO_CALCULATE').val();
        if (value == 1) {
            $('#INTEREST-label').hide();
            $('#INTEREST-element').hide();
            $('#COSTS-label').hide();
            $('#COSTS-element').hide();
        } else {
            $('#INTEREST-label').show();
            $('#INTEREST-element').show();
            $('#COSTS-label').show();
            $('#COSTS-element').show();
        }

    }
    autoCalculate();
</script>
<script>
    $(function() {
        $("#INVOICE_DATE").datepicker({dateFormat: 'dd/mm/yy', defaultDate: "-30"});
    });
    $(function() {
        $("#START_DATE").datepicker({dateFormat: 'dd/mm/yy', defaultDate: "-30"});
    });
</script>    
</div>
</div>
</div>
</div>