          <div class="aaa-theme-flex-row flex-content-row">
          
		  <div class="col-1">
            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("edit_ref_c") ?></h2></div>
                <div class="table-responsive">
				<div class="table-responsive form-group"><table class="table"><tr><td>
                 <form action="" class="aaa-theme-login-form" method="post" enctype="application/x-www-form-urlencoded">
                <?php
                if ($this->formSaved) {
                    print $this->Ok($this->G("saved_c"));
                }
                ?>
                <?php
                if ($this->formError) {
                    print $this->Error($this->G("not_all_fields_c"));
                }
                ?>
                <dl class="zend_form">
                    <?php print $this->form->REFERENCE_ID ?>
                    <?php print $this->form->REFERENCE_TYPE ?>
                    <?php print $this->form->TRAIN_TYPE ?>
                    <?php print $this->form->REFERENCE ?>
                    <?php print $this->form->STATE_ID ?>
                    <?php print $this->form->REFUND_STATEMENT ?>
                    <?php print $this->form->INVOICE_DATE ?>
                    <?php print $this->form->START_DATE ?>
                    <?php print $this->form->END_DATE ?>
                    <?php print $this->form->AMOUNT ?>
                    <?php print $this->form->AUTO_CALCULATE ?>
                    <?php print $this->form->INTEREST ?>
                    <?php print $this->form->COSTS ?>
                    <?php print $this->form->INTEREST_PERCENT ?>
                    <?php print $this->form->COST_PERCENT ?>
                    <?php print $this->form->INTEREST_MINIMUM ?>
                    <?php print $this->form->COST_MINIMUM ?>
                </dl>

				</td></tr></table>
              </div>
              </div>
                    <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("police") ?></h2></div>
                    <div class="table-responsive">
                        <table class="table"><tr><td>
                        <?php print $this->form->CONTRACT_NUMBER ?>
                        <?php print $this->form->CONTRACT_INSURED ?>
                        <?php print $this->form->CONTRACT_UY ?>
                        <?php print $this->form->CONTRACT_UNDERWRITER ?>
                        <?php print $this->form->CONTRACT_INCEPTIONDATE ?>
                        <?php print $this->form->CONTRACT_LINEOFBUSINESS ?>
                        <?php print $this->form->LEDGER_ACCOUNT ?>
                        <?php print $this->form->INVOICE_FROMDATE ?>
                        <?php print $this->form->INVOICE_TODATE ?>
                        </td></tr></table>
                    </div>
                </div>
            </div>
            <div class="col-1">
            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("dispute_c") ?></h2></div>
              	<div class="table-responsive">
                <table class="table">
                  <tbody>
                  <tr>
                      <td colspan="2">
                          <?php print $this->form->DISPUTE ?>
                          <?php if ($this->showDisputeContent === true) { ?>
                          <?php print $this->form->DISPUTE_STATUS ?>
                          <?php print $this->form->DISPUTE_COMMENT ?>
                          <?php print $this->form->DISPUTE_DATE ?>
                          <?php print $this->form->DISPUTE_DUEDATE ?>
                          <?php print $this->form->DISPUTE_ENDED_DATE ?>
                          <?php print $this->form->DISPUTE_ASSIGNEE ?>
                          <?php print $this->form->DISPUTE_AMOUNT ?>
                          <?php } ?>
                          <?php print $this->form->submit ?>
                      </td>
                  </tr>
                  <?php if ($this->showDisputeContent === true) { ?>
                  <tr>
	                  <td><b><?php $this->T("debtor_dispute_comment_c") ?></b></td>
    	              <td><?php
                            if($this->debtorDisputeComment) {
                                print $this->debtorDisputeComment;
                            } else {
                                $this->T("no_debtor_dispute_comment_found_c");
                            } ?>
					  </td>                    
                    </tr> 
                    <tr>
	                  <td><b><?php $this->T("debtor_dispute_phone_c") ?></b></td>
    	              <td>
                      <?php
                            if($this->debtorDisputePhone) {
                                print $this->debtorDisputePhone;
                            } else {
                                $this->T("no_debtor_dispute_phone_found_c");
                            } ?>
                      </td>                    
                    </tr> 
                    <tr>
	                  <td><b><?php $this->T("debtor_dispute_email_c") ?></b></td>
    	              <td>
					   <?php
                            if($this->debtorDisputeEmail) {
                                print $this->debtorDisputeEmail;
                            } else {
                                $this->T("no_debtor_dispute_email_found_c");
                            } ?>
					  </td>                    
                    </tr>
                  <?php } ?>
                  </tbody>
                </table>
               </div> 

			  <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("related_documents_c") ?></h2></div>
              <div class="table-responsive">

              
			  <?php if(count($this->documents) > 0) { ?>
              <table class="table"><tr><td>
			  <table class="table">
                    
                            <thead>
                            <tr>
                                <td><?php $this->T("document_name_c") ?></td>
                                <td><?php $this->T("document_description_c") ?></td>
                            </tr>
                            </thead>
							<tbody>
                            <?php foreach($this->documents as $document) { ?>
                                <tr>
                                    <td><?php echo $document->FILENAME ?></td>
                                    <td><?php echo $document->DESCRIPTION ?></td>
                                </tr>
                            <?php } ?>
							<tbody>
                        </table>
                          </td></tr></table>
                    <?php } else { ?>
                  <table class="table"><tr><td>
                        <p><?php $this->T("no_documents_found_c") ?></p>
                          </td></tr></table>
                    <?php } ?>                  
              </div>
			</div>
          </form>