<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>
<table id="data" class="tablesorter ws_data_table" width="100%">
    <thead>
        <tr>
            <th><?php $this->T("invoice_c"); ?></th>
            <th><?php $this->T("factuurdatum_c"); ?></th>
            <th><?php $this->T("start_date_c"); ?></th>
            <?php if ($this->showIntrestCosts) {  ?>
            <th><?php $this->T("end_date_c"); ?></th>
            <?php } ?>
            <th><?php $this->T("amount_c"); ?></th>
            <?php if ($this->showIntrestCosts) {  ?>
            <th><?php $this->T("costs_c"); ?></th>
            <th><?php $this->T("interest_c"); ?></th>
            <th><?php $this->T("total_c"); ?></th>
            <?php } ?>
            <th><?php $this->T("saldo_c"); ?></th>
            <th><?php $this->T("dispute_c"); ?></th>
            <th><?php $this->T("state_c"); ?></th>
            <th><?php $this->T("train_type_c"); ?></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) {
            if(!empty($row->DISPUTE)) {
                $class = " class='dispute' ";
            }
            elseif ($row->START_DATE <= date("Y-m-d")) {
                $class = " class='due' ";
            } else {
                $class = "";
            }
            ?>
            <tr <?php echo $class ?>>
                <td><?php echo $row->REFERENCE ?></td>
                <td><?php echo $this->Date($row->INVOICE_DATE) ?></td>
                <td><?php echo $this->Date($row->START_DATE) ?></td>
                <?php if ($this->showIntrestCosts) {  ?>
                <td><?php echo $this->Date($row->END_DATE) ?></td>
                <?php } ?>
                <td align="right"><?php echo $this->Amount($row->AMOUNT) ?></td>
                <?php if ($this->showIntrestCosts) {  ?>
                <td align="right"><?php echo $this->Amount($row->COSTS) ?></td>
                <td align="right"><?php echo $this->Amount($row->INTEREST) ?></td>
                <td align="right"><?php echo $this->Amount($row->TOTAL) ?></td>
                <?php } ?>
                <td align="right"><?php echo $this->Amount($row->SALDO) ?></td>
                <td align="center"><?php echo $this->Selection($row->DISPUTE) ?></td>
                <td><?php echo $row->STATE_CODE ?></td>
                <td><?php echo $row->TRAIN_TYPE ?></td>
                <td><?php if (!empty($this->manageInvoices)) { ?><a href="<?php echo $this->location() ?>/file-invoices/edit/id/<?php echo $row->REFERENCE_ID ?>/index/<?php echo $this->index ?>" ><span title ="<?php $this->T("edit_c") ?>"  class="ui-icon ui-icon-zoomin"></span><?php } ?></td>
                <td><?php if (!empty($this->manageInvoices)) { echo $this->Delete($this->location()."/file-invoices/view/delete/".$row->REFERENCE_ID."/index/".$this->index, $row->REFERENCE); } ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="12" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</table>
