<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>

		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("invoice_c"); ?></th>
						<td><?php $this->T("factuurdatum_c"); ?></td>
						<td><?php $this->T("start_date_c"); ?></td>
						<?php if ($this->showIntrestCosts) {  ?>
						<td><?php $this->T("end_date_c"); ?></td>
						<?php } ?>
						<td><?php $this->T("amount_c"); ?></td>
						<?php if ($this->showIntrestCosts) {  ?>
						<td><?php $this->T("costs_c"); ?></td>
						<td><?php $this->T("interest_c"); ?></td>
						<td><?php $this->T("total_c"); ?></td>
						<?php } ?>
						<td><?php $this->T("saldo_c"); ?></td>
						<td><?php $this->T("dispute_c"); ?></td>
						<td><?php $this->T("state_c"); ?></td>
						<td><?php $this->T("train_type_c"); ?></td>
						<td></td>
						<td></td>
                      </tr>
                    </thead>
                    <tbody>
<?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) {
          
            ?>
            <tr>
                <td><?php echo $row->REFERENCE ?></td>
                <td><?php echo $this->Date($row->INVOICE_DATE) ?></td>
                <td><?php echo $this->Date($row->START_DATE) ?></td>
                <?php if ($this->showIntrestCosts) {  ?>
                <td><?php echo $this->Date($row->END_DATE) ?></td>
                <?php } ?>
                <td align="right"><?php echo $this->Amount($row->AMOUNT) ?></td>
                <?php if ($this->showIntrestCosts) {  ?>
                <td align="right"><?php echo $this->Amount($row->COSTS) ?></td>
                <td align="right"><?php echo $this->Amount($row->INTEREST) ?></td>
                <td align="right"><?php echo $this->Amount($row->TOTAL) ?></td>
                <?php } ?>
                <td align="right"><?php echo $this->Amount($row->SALDO) ?></td>
                <td align="center"><?php echo $this->GoodBad(!$row->DISPUTE) ?></td>
                <td><?php echo $row->STATE_CODE ?></td>
                <td><?php echo $row->TRAIN_TYPE ?></td>
                <td><?php if (!empty($this->manageInvoices)) { ?><a href="<?php echo $this->location() ?>/file-invoices/edit/id/<?php echo $row->REFERENCE_ID ?>/fileId/<?php echo $this->fileId ?>" ><li class="fa fa-pencil fa-fw"></span><?php } ?></td>
                <td><?php if (!empty($this->manageInvoices)) { echo $this->Delete($this->location()."/file-invoices/view/delete/".$row->REFERENCE_ID."/fileId/".$row->FILE_ID, $row->REFERENCE); } ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="12" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>                 
                    </tbody>
                  </table>    
                </div>                          
              </div>

		  
