
          <div class="aaa-theme-flex-row flex-content-row">
          <div class="col-1">

            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("general_c") ?></h2></div>
                <div class="table-responsive">
				<div class="table-responsive form-group">
                <?php
                if ($this->generalFormSaved) {
                    print $this->Ok($this->G("saved_c"));
                }
                ?>
                <?php
                if ($this->generalPassError) {
                    print $this->Error($this->G("password_incorrect_c"));
                }
                ?>
                <?php
                if ($this->generalClientCodeError) {
                    print $this->Error($this->G("code_exists_c"));
                }
                ?>                <?php
                if ($this->generalFormError) {
                    print $this->Error($this->G("not_all_fields_c"));
                }
                ?>

                 <form enctype="application/x-www-form-urlencoded" method="post" class="aaa-theme-login-form">
                                <?php print $this->generalForm->CODE ?>
                                <?php print $this->generalForm->PASSWORD ?>
                                <?php print $this->generalForm->PASSWORD2 ?>
                                <?php print $this->generalForm->NAME ?>
                                <?php print $this->generalForm->ADDRESS ?>
                                <?php print $this->generalForm->ZIP_CODE ?>
                                <?php print $this->generalForm->CITY ?>
                                <?php print $this->generalForm->COUNTRY_ID ?>
                                <?php print $this->generalForm->LANGUAGE_ID ?>
                                <?php print $this->generalForm->MAINCLIENT ?>
                                <?php print $this->generalForm->E_MAIL ?>
                                <?php print $this->generalForm->TELEPHONE ?>
                                <?php print $this->generalForm->TELEFAX ?>
                                <?php print $this->generalForm->TRAIN_TYPE ?>
                                <?php print $this->generalForm->REMARKS ?>								
                                <?php print $this->generalForm->SUBMIT ?>
              </div>
              </div>
            </div>   
            </div>
            <div class="col-1"> 
            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("invoice_settings_c") ?></h2></div>
              	<div class="table-responsive">
								<?php print $this->generalForm->VAT_NO ?>
                                <?php print $this->generalForm->INVOICE_CONTACT ?>
                                <?php print $this->generalForm->INVOICE_ADDRESS ?>
                                <?php print $this->generalForm->INVOICE_ZIP_CODE ?>
                                <?php print $this->generalForm->INVOICE_CITY ?>
                                <?php print $this->generalForm->INVOICE_COUNTRY_ID ?>
                                <?php print $this->generalForm->COMPENSATED ?>
                                <?php print $this->generalForm->BANK_ACCOUNT_NR ?>
                                <?php print $this->generalForm->SUBMIT ?>
               </div>              
            </div>
            </div>
            <div class="col-1">
            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
              <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("amounts_c") ?></h2></div>
              <div class="table-responsive">
                <table class="table">
                  <tbody>
                    <tr>
	                  <td><b><?php $this->T("amount_c") ?></b></td>
    	              <td><?php echo $this->Amount($this->file->AMOUNT) ?></td>                    
                    </tr> 
                    <tr>
	                  <td><b><?php $this->T("payed_c") ?></b></td>
    	              <td><?php echo $this->Amount($this->file->PAYED_AMOUNT) ?></td>                    
                    </tr> 
                    <tr>
	                  <td><b><?php $this->T("saldo_c") ?></b></td>
    	              <td><?php echo $this->Amount($this->file->SALDO_AMOUNT) ?></td>                    
                    </tr> 
					<?php if ($this->showIntrestCosts) {  ?>
					<tr>
						<td class="label"><?php $this->T("costs_c") ?></td>
						<td align="right"><?php echo $this->Amount($this->file->COSTS) ?></td>
						<td align="right"><?php echo $this->Amount($this->file->PAYED_COSTS) ?></td>
						<td align="right"><?php echo $this->Amount($this->file->SALDO_COSTS) ?></td>
					</tr>
					<tr>
						<td class="label"><?php $this->T("intrests_c") ?></td>
						<td align="right"><?php echo $this->Amount($this->file->INTEREST) ?></td>
						<td align="right"><?php echo $this->Amount($this->file->PAYED_INTEREST) ?></td>
						<td align="right"><?php echo $this->Amount($this->file->SALDO_INTEREST) ?></td>
					</tr>
					<tr>
						<td class="label"><?php $this->T("incasso_kost_c") ?></td>
						<td align="right"><?php echo $this->Amount($this->file->INCASSOKOST) ?></td>
						<td align="right"><?php echo $this->Amount($this->file->PAYED_UNKNOWN) ?></td>
						<td align="right"><?php echo $this->Amount($this->file->INCASSOKOST - $this->file->PAYED_UNKNOWN) ?></td>
					</tr>
					<tfoot>
						<tr>
							<td class="footer"><?php $this->T("total_c") ?></td>
							<td align="right"><?php echo $this->Amount($this->file->TOTAL + $this->file->INCASSOKOST) ?></td>
							<td align="right"><?php echo $this->Amount($this->file->PAYED_TOTAL) ?></td>
							<td align="right"><?php echo $this->Amount($this->file->PAYABLE + $this->file->INCASSOKOST - $this->file->PAYED_UNKNOWN) ?></td>
						</tr>
					</tfoot>
					<?php } ?>
                  </tbody>
                </table>
               </div>
              <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("info_c") ?></h2></div>
              <div class="table-responsive">
              <form action="index.html" class="aaa-theme-login-form" method="post" enctype="multipart/form-data">
                <table class="table">
                  <tbody>                    
                    <tr>
	                  <td><strong><?php $this->T("gem_betalingstermijn_c") ?></strong></td> 
					<?php if($this->nrOfPayments > 0) { ?>
						<td><?php echo $this->paymentDelay ?> (<?php $this->T("based_on_payments_c") ?>: <?php echo $this->nrOfPayments ?>)</td>
					<?php } else { ?>
						<td><?php echo $this->T("insufficient_data_for_delay_c") ?></td>
					<?php } ?>
					<?php print $this->creditlimiteForm; ?>
                     <tr>
	                  <td>&nbsp;</td>
    	              <td><button type="submit" class="aaa-theme-orange-button">Update</button></td>                    
                    </tr> 
                  </tbody>
                </table>
              </form>
              </div>  
            </div>
          </div>
          </div>
          <div class="aaa-theme-flex-row flex-content-row">
          <div class="col-1">
            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
              <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("laatste_c") ?> <?php $this->T("actions_c") ?></h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("action_date_c"); ?></td>
                        <td><?php $this->T("code_c"); ?></td>
                        <td><?php $this->T("description_c"); ?></td>
						<td>&nbsp;</td>
                      </tr>
                    </thead>
                    <tbody>
					  <?php if (!empty($this->actions)) { ?>
                      <?php foreach ($this->actions as $row) { ?>
                      <tr>
                                <td><?php echo $this->Date($row->ACTION_DATE) ?></td>
                                <td><?php echo $row->ACTION_CODE ?></td>
                                <td><?php echo $row->ACTION_DESCRIPTION ?></td>
                                <td><?php if (!empty($row->TEMPLATE_CONTENT) && !empty($this->viewActionContent)) { ?>
                                    <a href="<?php echo $this->location() ?>/print/template/fileActionId/<?php echo $row->FILE_ACTION_ID ?>"
                                       target="_blank"><span title="<?php $this->T("view_c") ?>" class="ui-icon ui-icon-disk"></span>
                                    <?php } ?></td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
					<tr>
                            <td colspan="4">
                                <?php $this->T("no_results_c"); ?>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                  </table>      
                </div>                          
              </div>
              </div>
              <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
              <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("laatste_c") ?> <?php $this->T("remarks_c") ?></h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("date_c"); ?></td>
                        <td><?php $this->T("remark_c"); ?></td>
                        <td><?php $this->T("by_c"); ?></td>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if (!empty($this->remarks)) { ?>
                        <?php foreach ($this->remarks as $row) { ?>
                            <tr>
                                <td><?php echo $this->Date($row->CREATION_DATE) ?></td>
                                <td><?php echo substr($row->REMARK, 0, 50) ?></td>
                                <td><?php echo $row->CREATION_USER ?></td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="3">
                                <?php $this->T("no_results_c"); ?>
                            </td>
                        </tr>
                    <?php } ?>                               
                    </tbody>
                  </table>       
                </div>                          
              </div>
            </div>
            <div class="col-1">
            <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
              <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("laatste_c") ?> <?php $this->T("payments_c") ?></h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T("date_c"); ?></td>
                        <td><?php $this->T("amount_c"); ?></td>
                        <td><?php $this->T("account_c"); ?></td>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if (!empty($this->payments)) { ?>
                        <?php foreach ($this->payments as $row) { ?>
                            <tr>
                                <td><?php echo $this->Date($row->PAYMENT_DATE) ?></td>
                                <td align="right"><?php echo $this->Amount($row->AMOUNT) ?></td>
                                <td><?php echo $row->ACCOUNT_CODE ?></td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="3">
                                <?php $this->T("no_results_c"); ?>
                            </td>
                        </tr>
                    <?php } ?>                    
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>                        
          </div> <!-- Second row ends -->



