                <?php
                if ($this->generalFormSaved) {
                    print $this->Ok($this->G("saved_c"));
                }
                ?>
                <?php
                if ($this->generalPassError) {
                    print $this->Error($this->G("password_incorrect_c"));
                }
                ?>
                <?php
                if ($this->generalFormError) {
                    print $this->Error($this->G("not_all_fields_c"));
                }
                ?> 
 <form enctype="application/x-www-form-urlencoded" method="post" action="">
		  <div class="aaa-theme-flex-row flex-content-row">
		  
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("general_c") ?></h2></div>
                <div class="table-responsive">
                                <?php print $this->generalForm->CODE ?>
                                <?php print $this->generalForm->PASSWORD ?>
                                <?php print $this->generalForm->PASSWORD2 ?>
                                <?php print $this->generalForm->NAME ?>
                                <?php print $this->generalForm->ADDRESS ?>
                                <?php print $this->generalForm->ZIP_CODE ?>
                                <?php print $this->generalForm->CITY ?>
                                <?php print $this->generalForm->COUNTRY_ID ?>
                                <?php print $this->generalForm->LANGUAGE_ID ?>
                                <?php print $this->generalForm->MAINCLIENT ?>
                                <?php print $this->generalForm->E_MAIL ?>
                                <?php print $this->generalForm->TELEPHONE ?>
                                <?php print $this->generalForm->TELEFAX ?>
                                <?php print $this->generalForm->TRAIN_TYPE ?>
                                <?php print $this->generalForm->REMARKS ?>
                                <?php print $this->generalForm->SUBMIT ?>
                </div>                          
              </div>
            </div>  
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("invoice_settings_c") ?></h2></div>
                <div class="table-responsive">
                                <?php print $this->generalForm->VAT_NO ?>
                                <?php print $this->generalForm->INVOICE_CONTACT ?>
                                <?php print $this->generalForm->INVOICE_ADDRESS ?>
                                <?php print $this->generalForm->INVOICE_ZIP_CODE ?>
                                <?php print $this->generalForm->INVOICE_CITY ?>
                                <?php print $this->generalForm->INVOICE_COUNTRY_ID ?>
                                <?php print $this->generalForm->COMPENSATED ?>
                                <?php print $this->generalForm->BANK_ACCOUNT_NR ?>
                                <?php print $this->generalForm->SUBMIT ?>
                </div>                          
              </div>
            </div>  
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("Client_Conditions_c") ?></h2></div>
                <div class="table-responsive">
                                <?php print $this->generalForm->CURRENT_INTREST_PERCENT ?>
                                <?php print $this->generalForm->CURRENT_INTREST_MINIMUM ?>
                                <?php print $this->generalForm->CURRENT_COST_PERCENT ?>
                                <?php print $this->generalForm->CURRENT_COST_MINIMUM ?>
                                <?php print $this->generalForm->ARTICLE ?>
                                <?php print $this->generalForm->COURT ?>
                                <?php print $this->generalForm->ACTIVITIES ?>
                                <?php print $this->generalForm->TEMPLATE_FOOTER ?>
                                <?php print $this->generalForm->SUBMIT ?>
                </div>                          
              </div>
            </div>         
          </div> 
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T("contacts_c") ?></h2></div>
                <div class="table-responsive">
                	

                  <table class="table table-striped table-bordered">
                    <thead>
                                        <tr>
                                            <td><?php $this->T("function_c"); ?></td>
                                            <td><?php $this->T("name_c"); ?></td>
                                            <td><?php $this->T("email_c"); ?></td>
                                            <td><?php $this->T("address_c"); ?></td>
                                            <td><?php $this->T("tel_c"); ?></td>
                                            <td><?php $this->T("language_c"); ?></td>
                                        </tr>
                    </thead>
                    <tbody>
                      <?php if (!empty($this->contacts)) { ?>
                                        <?php foreach ($this->contacts as $row) { ?>
                                            <tr>
                                                <td><?php echo $row->FUNCTION_DESCRIPTION ?></td>
                                                <td><?php echo $row->NAME ?></td>
                                                <td><?php echo $row->EMAIL ?></td>
                                                <td><?php echo $row->ADDRESS ?></td>
                                                <td><?php echo $row->TEL ?></td>
                                                <td><?php echo $row->LANGUAGE ?></td>
                                            </tr>
                                        <?php } ?>
                                    <?php } else { ?>
                                        <tr>
                                            <td colspan="8" class="no_results">
                                                <?php $this->T("no_results_c"); ?>
                                            </td>
                                        </tr>
                                    <?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> </form><!-- Second row ends -->
