<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->headerTitle?></title>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/font-awesome.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/bootstrap.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/aaa-theme-style.css') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-1.11.2.min.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-migrate-1.2.1.min.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/aaa-theme-script.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/app.js') ?>
        
		<?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/start/jquery-ui-1.10.4.custom.css') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-ui-1.10.4.custom.js') ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- amCharts javascript sources -->
    	
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/amcharts.js') ?>
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/am/pie.js') ?>
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/am/gauge.js') ?>
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/am/serial.js') ?>
		
	<!-- FancyBox -->
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/fancybox/source/jquery.fancybox.pack.js') ?>
		<?php echo $this->headLink()->appendStylesheet(BASE_URL . 'js/fancybox/source/jquery.fancybox.css') ?>
        <script type="text/javascript">
            var appInfo = {
                'resourcePath' : '<?php echo $this->baseHttp ?>'
            }
        </script>
		
  </head>
  <body>  
<!-- Left column not needed -->
    <div class="aaa-theme-flex-row">      
      <!-- Main content --> 
      <div class="aaa-theme-content col-1 light-gray-bg">
        <div class="aaa-theme-top-nav-container">
          <div class="row">
			<table width="100%"><tr>
			<td align="left">
			<?php if ($this->indexes['prevIndex'] >=0 && !empty($this->indexes)) { ?><a href="<?php echo $this->location() ?>/debtor-detail/view/index/<?php echo $this->indexes['prevIndex'] ?>"> <li class="fa fa-arrow-circle-left"></li></a> <?php } ?>
			</td>
			<td align="center">
            <h2 class="text-uppercase">
			<?php print $this->T("debtor_c") ?> : <?php echo $this->debtor->NAME ?>
			</h2>
			</td>
			<td align="right">
			<?php if ($this->indexes['nextIndex'] >=0 && !empty($this->indexes)) { ?><a href="<?php echo $this->location() ?>/debtor-detail/view/index/<?php echo $this->indexes['nextIndex'] ?>"> <li class="fa fa-arrow-circle-right"></li></a><?php } ?>
            </td></tr></table>
			<br /><br />
			<nav class="aaa-theme-top-nav col-lg-12 col-md-12">
              <ul class="text-uppercase">
                <li><a  href="<?php echo $this->location() ?>/debtor-detail/view/index/<?php echo $this->index ?>"><?php print $this->T("general_c") ?></a></li>
                <li><a href="<?php echo $this->location() ?>/file-detail/view/fileId/<?php echo $this->debtorFileId ?>"><?php print $this->T("file_c") ?></a></li>
                <li><a href="<?php echo $this->location() ?>/debtor-history/view/index/<?php echo $this->index ?>"><?php print $this->T("address_history_c") ?></a></li>
                <li><a href="<?php echo $this->location() ?>/debtor-contacts/view/index/<?php echo $this->index ?>"><?php print $this->T("contacts_c") ?></a></li>
				<?php if(count($this->subdebtors) > 0) { ?>
                <li><a href="<?php echo $this->location() ?>/debtor-subdebtors/view/index/<?php echo $this->index ?>"><?php print $this->T("subdebtors_c") ?></a></li>
				<?php } ?>
              </ul>  
            </nav> 
          </div>
        </div>

       <!-- main content -->
		
               <div class="aaa-theme-content-container">
			   <?php if (($this->printButton) OR ($this->addButton) OR ($this->printButton)) { ?>
				  <div class="aaa-theme-flex-row flex-content-row aaa-theme-overflow-hidden"> <!-- overflow hidden for iPad mini landscape view-->
					<div class="col-1">              
					  <div class="aaa-theme-content-widget no-padding light-gray-bg col-1 text-center">
					  <table class="responsive" width="100%">
					  <tr bg>
						<td align="left">&nbsp;</td>
						<td align="right"><?php if (!empty($this->bread)) { ?><i><?php echo $this->bread ?></i><?php } ?>
						
							<?php if ($this->addButton) { ?><a style="cursor: pointer" href="<?php echo $this->Location() ?><?php echo $this->addButton ?>" title="<?php $this->T("add_c") ?>"><li class="fa fa-plus-square-o fa-fw"></li></a><?php } ?>
							<?php if ($this->exportButton) { ?><a style="cursor: pointer" href="<?php echo $this->Location() ?>/export/csv"><li class="fa fa-floppy-o fa-fw"></li></a><?php } ?>
							<?php if ($this->printButton) { ?><a style="cursor: pointer" onclick="window.print()"><li class="fa fa-print fa-fw"></li></a><?php } ?>
						
						</td>
					  </tr>
					  </table>	   
					</div>        
					</div> 
				  </div>  
					<?php } ?>				  
					  <?php echo $this->layout()->content ?>
						
						
						
                    <script>
<?php
if (!empty($this->errors)) {
    foreach ($this->errors as $key => $error) {
        if (!empty($error)) {
            ?>
                                    $("#<?php echo $key; ?>").addClass("errorfield");
            <?php
        }
    }
}
?>
                    </script>
                    <footer class="text-right">
            <p>&copy; Triple-A Solutions</p>
          </footer>         
        </div>
      </div>
    </div>
    
 <script type="text/javascript">
$('input').addClass('form-control');
$('select').addClass('form-control');
$('checkbox').addClass('form-control');
$('input[type=submit]').addClass('aaa-theme-orange-button');
</script>

  </body>
</html>