<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->headerTitle ?></title>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/global.css') ?>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/start/jquery-ui-1.10.4.custom.css') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-1.10.2.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-ui-1.10.4.custom.js') ?>
        <?php //echo $this->headScript()->appendFile(BASE_URL . 'js/jquery.tablesorter.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/app.js') ?>
        <style>
            div#addButton{
                position:absolute;
                right: 5px;
                z-index: 100;
                top : 40px;
            }     
        </style>
        <style type="text/css">
            @media print {
                .noprint { display: none; }
            }
        </style>
        <style>
            .ui-autocomplete-loading { background: white url('images/ui-anim_basic_16x16.gif') right center no-repeat; }
        </style>
    </head>
    <body>
        <div id="addButton"  class="noprint">
            <?php if ($this->addButton) { ?><div onClick=location.href="<?php echo $this->Location() ?><?php echo $this->addButton ?>"  class="ui-state-default ui-corner-all" title="<?php $this->T("add_c") ?>"><span class="ui-icon ui-icon-plus"></span></div><?php } ?>
            <?php if ($this->exportButton) { ?><div onClick=location.href="<?php echo $this->Location() ?>/export/csv" class="ui-state-default ui-corner-all" title="<?php $this->T("export_csv_c") ?>"><span class="ui-icon ui-icon-disk"></span></div><?php } ?>
            <?php if ($this->printButton) { ?><div onClick="window.print()" class="ui-state-default ui-corner-all" title="<?php $this->T("print_content_c") ?>"><span class="ui-icon ui-icon-print"></span></div><?php } ?>
        </div>        

        <div id="content">
            <script>
                $(function() {
                    $(".menu").menu({position: {my: "left top"}});
                });
            </script>
            <div id="header" style="position: relative; width: 100%;" >
                <table width="100%" align="center">
                    <tr>
                        <td align="left"><?php if ($this->indexes['prevIndex'] != '') { ?><a href="<?php echo $this->location() ?>/file-detail/view/index/<?php echo $this->indexes['prevIndex'] ?>"> <span title ="<?php $this->T("view_file_c") ?>" class="ui-icon ui-icon-seek-prev"></span></a> <?php } ?></td>
                        <td align="center" class="title"><?php print $this->T("file_c") ?> : <?php echo $this->file->FILE_NR ?> - <?php echo $this->file->DEBTOR_NAME ?></td>
                        <td align="right"><?php if ($this->indexes['nextIndex'] != '') { ?><a href="<?php echo $this->location() ?>/file-detail/view/index/<?php echo $this->indexes['nextIndex'] ?>"> <span title ="<?php $this->T("view_file_c") ?>" class="ui-icon ui-icon-seek-next"></span></a><?php } ?></td>
                    </tr>
                </table>
                <div id="menu">
                    <table width="80%">
                        <tr>
                            <td>
                                <ul id="menu1" class="menu">
                                    <li><a href="<?php echo $this->location() ?>/file-detail/view/index/<?php echo $this->index ?>"><?php print $this->T("general_c") ?></a></li>
                                </ul>
                            </td>
                            <td>
                                <ul id="menu2" class="menu">
                                    <li><a href="<?php echo $this->location() ?>/file-invoices/view/index/<?php echo $this->index ?>"><?php print $this->T("references_c") ?></a></li>
                                </ul>
                            </td>
                            <td>
                                <ul id="menu4" class="menu">
                                    <li><a href="<?php echo $this->location() ?>/file-actions/view/index/<?php echo $this->index ?>"><?php print $this->T("actions_c") ?></a></li>
                                </ul>
                            </td>
                            <td>
                                <ul id="menu5" class="menu">
                                    <li><a href="<?php echo $this->location() ?>/file-payments/view/index/<?php echo $this->index ?>"><?php print $this->T("payments_c") ?></a></li>
                                </ul>
                            </td>
                            <td>
                                <ul id="menu6" class="menu">
                                    <li><a href="<?php echo $this->location() ?>/file-documents/view/index/<?php echo $this->index ?>"><?php print $this->T("documents_c") ?></a></li>
                                </ul>
                            </td>
                            <?php if ($this->showFileRemarks === true) { ?> 
                                <td>
                                    <ul id="menu7" class="menu">
                                        <li><a href="<?php echo $this->location() ?>/file-remarks/view/index/<?php echo $this->index ?>"><?php print $this->T("remarks_c") ?></a></li>
                                    </ul>
                                </td>
                                <td>
                                    <ul id="menu8" class="menu">
                                        <li><a href="<?php echo $this->location() ?>/file-imported-mails/view/index/<?php echo $this->index ?>"><?php print $this->T("imported_mails_c") ?></a></li>
                                    </ul>
                                </td>
                            <?php } ?>
                            <?php if ($this->showFileTodos === true) { ?> 
                                <td>
                                    <ul id="menu9" class="menu">
                                        <li><a href="<?php echo $this->location() ?>/file-todos/view/index/<?php echo $this->index ?>"><?php print $this->T("todos_c") ?></a></li>
                                    </ul>
                                </td>
                            <?php } ?>
                            <?php if ($this->showFileCosts === true) { ?> 
                                <td>
                                    <ul id="menu10" class="menu">
                                        <li><a href="<?php echo $this->location() ?>/file-costs/view/index/<?php echo $this->index ?>"><?php print $this->T("costs_c") ?></a></li>
                                    </ul>
                                </td>
                            <?php } ?>
                        </tr>
                    </table>
                </div>

            </div>
            <br><br>
                    <div id="actioncontent">
                        <?php echo $this->layout()->content ?>
                    </div>
                    <script>
<?php
if (!empty($this->errors)) {
    foreach ($this->errors as $key => $error) {
        if (!empty($error)) {
            ?>
                                    $("#<?php echo $key; ?>").addClass("errorfield");
            <?php
        }
    }
}
?>
                    </script>
                    </div>
                    </body>
                    </html>