<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->headerTitle?></title>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/font-awesome.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/bootstrap.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/aaa-theme-style.css') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-1.11.2.min.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-migrate-1.2.1.min.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/aaa-theme-script.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/app.js') ?>
		
		<?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/start/jquery-ui-1.10.4.custom.css') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-ui-1.10.4.custom.js') ?>
        

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- amCharts javascript sources -->
    	
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/amcharts.js') ?>
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/am/pie.js') ?>
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/am/gauge.js') ?>
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/am/serial.js') ?>
		
	<!-- FancyBox -->
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/fancybox/source/jquery.fancybox.pack.js') ?>
		<?php echo $this->headLink()->appendStylesheet(BASE_URL . 'js/fancybox/source/jquery.fancybox.css') ?>



  </head>
  <body>  
<!-- Left column -->
    <div class="aaa-theme-flex-row">
      <div class="aaa-theme-sidebar">
        <div class="profile-photo-container">
          <img src="<?php echo $this->location() ?>/public/images/logo.jpg" alt="AAA - Solutions" class="img-responsive"><br />
          <p align="center"><a class="active" href="<?php echo $this->location() ?>/index/index/selectlang/NL">NL</a> - <a href="<?php echo $this->location() ?>/index/index/selectlang/FR">FR</a> - <a href="<?php echo $this->location() ?>/index/index/selectlang/EN">EN</a></p>
          <!-- <p><?php echo $this->T("welcome_c") ?> <?php echo $this->Welcome(); ?></p> -->
        </div>
        <!-- Search box -->
        <!-- HIDDEN
        <form class="aaa-theme-search-form" role="search">
          <div class="input-group">
              <button type="submit" class="fa fa-search"></button>
              <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
          </div>
        </form>
        -->
        <div class="mobile-menu-icon">
            <i class="fa fa-bars"></i>
          </div>
        <nav class="aaa-theme-left-nav">
          <ul>
          <?php
          if (!empty($this->menu)) {
          foreach ($this->menu as $id => $menu) {
          ?>
          
            <?php if ($this->menu[$id]['NAV'] == $this->nav or $this->currentMenu['NAV'] == $this->menu[$id]['NAV'] ) {
                  $active = "class='active'";
              } else {
                  $active = "";
              }
              ?>
              <li> <a  href="<?php echo $this->Location() ?>/<?php echo $this->menu[$id]['NAV']?>" <?php echo $active?>><?php if (!empty($menu['ICON'])) { ?><i class="fa fa-<?php echo $menu['ICON']?> fa-fw"><?php } ?></i><?php echo $menu['TITEL'] ?></a></li>
          <?php 
		  }}		  
		  ?>
          
            <li><a href="<?php echo $this->Location() ?>/Auth/Logout"><i class="fa fa-eject fa-fw"></i><?php $this->T('logout_c') ?></a></li>
          </ul>
        </nav>
      </div>
      <!-- Submenu content --> 
      <div class="aaa-theme-content col-1 light-gray-bg">
        <div class="aaa-theme-top-nav-container">
          <div class="row">
            <nav class="aaa-theme-top-nav col-lg-12 col-md-12">
              <ul class="text-uppercase">
                  <?php if (!empty($this->currentMenu['SUBMENU'])) {
                      foreach ($this->currentMenu['SUBMENU'] as $submenu) {
                          if ($submenu['NAV'] == $this->nav) {
                              $active = "class='active'";
                          } else {
                              $active = "";
                          }
                          ?>
                          <li> <a  href="<?php echo $this->Location() ?>/<?php echo $submenu['NAV']?>" <?php echo $active?>><?php echo $submenu['TITEL'] ?></a></li>
                          <?php
                      }
                  }
                  ?>
              </ul>
            </nav> 
          </div>
        </div>
        
        <!-- main content -->
               <div class="aaa-theme-content-container">
				  <div class="aaa-theme-flex-row flex-content-row aaa-theme-overflow-hidden"> <!-- overflow hidden for iPad mini landscape view-->
					<div class="col-1">              
					  <div class="aaa-theme-content-widget white-bg col-1 text-center">
					  <table class="responsive" width="100%">
					  <tr>
						<td align="left"><?php echo $this->T("welcome_c") ?> <?php echo $this->Welcome(); ?></td>
						<td align="right"><?php if (!empty($this->bread)) { ?><i><?php echo $this->bread ?></i>  <?php } ?>
						
							<?php if ($this->addButton) { ?><a style="cursor: pointer" href="<?php echo $this->Location() ?><?php echo $this->addButton ?>" title="<?php $this->T("add_c") ?>"><li class="fa fa-plus-square-o fa-fw"></li></a><?php } ?>
							<?php if ($this->addButtonParent) { ?><a style="cursor: pointer" href="<?php echo $this->Location() ?><?php echo $this->addButtonParent ?>" title="<?php $this->T("add_c") ?>"><li class="fa fa-plus-square-o fa-fw"></li></a><?php } ?>
							<?php if ($this->exportButton) { ?><a style="cursor: pointer" onClick=location.href="<?php echo $this->Location() ?>/export/csv" title="<?php $this->T("export_csv_c") ?>"><li class="fa fa-floppy-o fa-fw"></li></a><?php } ?>
							<?php if ($this->printButton) { ?><a style="cursor: pointer" onClick="window.print()" title="<?php $this->T("print_content_c") ?>"><li class="fa fa-print fa-fw"></li></a><?php } ?>
						
						</td>
					  </tr>
					  </table>					   
					</div>        
					</div> 
				  </div>
				
                
                <?php echo $this->layout()->content ?>
			
            <footer class="text-right">
            <p>&copy; <?php echo $this->headerTitle?></p>
          </footer>  
      		
                <script>
<?php if (!empty($this->errors)) {
    foreach ($this->errors as $key => $error) {
        if (!empty($error)) {
            ?>
                        $("#<?php echo $key; ?>").addClass("errorfield");
        <?php }
    }
}
?>
                </script>
 <script type="text/javascript">
$('input').addClass('form-control');
$('select').addClass('form-control');
$('checkbox').addClass('form-control');
$('input[type=submit]').addClass('aaa-theme-orange-button');
</script>
               
                       
        </div>
      </div>
    </div>
  </body>
</html>