<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->headerTitle?></title>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/font-awesome.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/bootstrap.min.css') ?>
        <?php echo $this->headLink()->appendStylesheet(BASE_URL . 'css/aaa-theme-style.css') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-1.11.2.min.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/jquery-migrate-1.2.1.min.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/aaa-theme-script.js') ?>
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/app.js') ?>
        

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- amCharts javascript sources -->
    	
        <?php echo $this->headScript()->appendFile(BASE_URL . 'js/amcharts.js') ?>
		<script type="text/javascript" src="http://cdn.amcharts.com/lib/3/pie.js"></script>
        <script type="text/javascript" src="http://www.amcharts.com/lib/3/gauge.js"></script>
        <script type="text/javascript" src="http://www.amcharts.com/lib/3/serial.js"></script>
		
	<!-- FancyBox -->
		<?php echo $this->headScript()->appendFile(BASE_URL . 'js/fancybox/source/jquery.fancybox.pack.js') ?>
		<?php echo $this->headLink()->appendStylesheet(BASE_URL . 'js/fancybox/source/jquery.fancybox.css') ?>
       
  </head>
  <body class="aaa-bg">

    <?php echo $this->layout()->content ?>
	
	                </script>
 <script type="text/javascript">
$('input').addClass('form-control');
$('select').addClass('form-control');
$('checkbox').addClass('form-control');
$('input[type=submit]').addClass('aaa-theme-orange-button');
</script>
    </body>


</html>