         <div class="aaa-theme-flex-row flex-content-row">
          <div class="col-1">

            <div class="panel panel-default aaa-theme-content-widget white-bg aaa-theme-overflow-hidden"><?php
if ($this->formSaved) {
    print $this->Ok($this->G("saved_c"));
}
?>
<?php
if ($this->formError) {
    print $this->Error($this->G("not_all_fields_c"));
}
if ($this->codeExistsError) {
    print $this->Error($this->G("code_exists_error_c"));
}
?>

<?php print $this->form ?>
</div></div></div>

          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                	

                  <table class="table table-striped table-bordered">
                    <thead>
						<tr>
							<td><?php $this->T('Field_c') ?></td>
							<td><?php $this->T('example_value_c') ?></td>
						</tr>
                    </thead>
					<tbody>
						<?php foreach($this->filesAllInfo as $field => $value): ?>
							<tr>
								<td><?php echo $field; ?></td>
								<td><?php echo $value ?></td>
							</tr>
						<?php endforeach; ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->


