<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php echo count($this->results) ?> resultaten gevonden</h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
						<tr>
							<td><?php $this->T("id_c"); ?></td>
							<td><?php $this->T("Code_c"); ?></td>
							<td><?php $this->T("Description_c"); ?></td>
							<td></td>
							<td></td>
						</tr>					
                    </thead>
					<tbody>
						<?php if (!empty($this->results)) { ?>
							<?php foreach ($this->results as $row) { ?>
								<tr>
									<td><?php echo $row->TEMPLATE_ID ?></td>
									<td><?php echo $row->CODE ?></td>
									<td><?php echo $row->DESCRIPTION ?></td>
									<td><a href="<?php echo $this->location() ?>/settings-templates/edit/id/<?php echo $row->TEMPLATE_ID ?>" ><li class="fa fa-search-plus fa-fw"></li></td>
									<td>
										<?php if($row->SYSTEM != 1): ?>
											<?php echo $this->Delete($this->location()."/settings-templates/view/delete/" . $row->TEMPLATE_ID , $row->CODE) ?>
										<?php endif; ?>
									</td>

								</tr>
							<?php } ?>
						<?php } else { ?>
							<tr>
								<td colspan="5" class="no_results">
									<?php $this->T("no_results_c"); ?>
								</td>
							</tr>
						<?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->
		  					
					
					
					
	