<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>
<div class="aaa-theme-flex-row flex-content-row">
    <div class="col-1">
        <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th><?php $this->T("type_c"); ?></th>
                        <th><?php $this->T("name_c"); ?></th>
                        <th><?php $this->T("email_c"); ?></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($this->results)) { ?>
                        <?php foreach ($this->results as $row) { ?>
                            <tr>
                                <td><?php echo $row->TYPE ?></td>
                                <td><?php echo $row->NAME ?></td>
                                <td><?php echo $row->EMAIL ?></td>
                                <td><?php echo $this->Delete($this->location() . "/settings-allowed-mails/view/delete/" . $row->EMAIL, "$row->EMAIL $row->NAME") ?></td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="5" class="no_results">
                                <?php $this->T("no_results_c"); ?>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div> <!-- Second row ends -->
