<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>
         <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php echo count($this->results) ?> resultaten gevonden</h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
 <tr>
        <th><?php $this->T("code_c"); ?></th>
        <th><?php $this->T("name_c"); ?></th>
        <th><?php $this->T("commission_delta_c"); ?></th>
        <th></th>
        <th></th>
    </tr>					
                    </thead>
					<tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->DESCRIPTION ?></td>
                <td><?php echo $row->DELTA ?></td>
                <td><a href="<?php echo $this->location() ?>/settings-countries/edit/id/<?php echo $row->COUNTRY_ID ?>" ><li class="fa fa-search-plus fa-fw"></li></td>
                <td>
                    <?php echo $this->Delete($this->location()."/settings-countries/view/delete/" . $row->COUNTRY_ID , $row->CODE) ?>
                </td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->
		  					
					
					
					
	
<h3><?php echo count($this->results) ?> resultaten gevonden</h3>
<table id="data" class="tablesorter ws_data_table" width="100%">
    <thead>
    <tr>
        <th><?php $this->T("code_c"); ?></th>
        <th><?php $this->T("name_c"); ?></th>
        <th><?php $this->T("commission_delta_c"); ?></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->DESCRIPTION ?></td>
                <td><?php echo $row->DELTA ?></td>
                <td><a href="<?php echo $this->location() ?>/settings-countries/edit/id/<?php echo $row->COUNTRY_ID ?>" ><span title ="<?php $this->T("edit_c") ?>"  class="ui-icon ui-icon-zoomin"></span></td>
                <td>
                    <?php echo $this->Delete($this->location()."/settings-countries/view/delete/" . $row->COUNTRY_ID , $row->CODE) ?>
                </td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</table>
