create table IMPORT$INVOICES (
DEVISION_CODE DOM_REFERENCE,
CLIENT_NUMBER DOM_REFERENCE,
CLIENT_NAME DOM_NAME,
CLIENT_ADDRESS DOM_ADDRESS,
CLIENT_ZIPCODE DOM_CODE,
CLIENT_PLACE DOM_CITY,
CLIENT_COUNTRY DOM_CODE,
CLIENT_LANGUAGE DOM_CODE,
CLIENT_TEL DOM_PHONE,
CLIENT_EMAIL DOM_EMAIL,
CLIENT_VAT DOM_REFERENCE,
INVOICE_TYPE DOM_REFERENCE,
INVOICE_NUMBER DOM_REFERENCE,
INVOICE_AMOUNT DOM_MONEY,
INVOICE_DATE DOM_DATE,
INVOICE_DUEDATE DOM_DATE,
CLIENT_ID DOM_RECORD_ID,
DEBTOR_ZIPCODE_ID DOM_RECORD_ID,
DEBTOR_ID DOM_RECORD_ID,
CREATION_DATE DOM_DATE
);


create index IDX_IMPORT_INVOICES_CLIENT  on IMPORT$INVOICES computed by (CLIENT_NUMBER);
create index IDX_IMPORT_INVOICES_CLIENT_ID  on IMPORT$INVOICES computed by (CLIENT_ID);
create index IDX_IMPORT_INVOICES_DEBTOR_ID  on IMPORT$INVOICES computed by (DEBTOR_ID);
create index IDX_IMPORT_INVOICES_FILE_ID  on IMPORT$INVOICES computed by (FILE_ID);



ALTER TABLE FILES$REFERENCES DROP REFERENCE_TYPE;
ALTER TABLE FILES$REFERENCES ADD REFERENCE_TYPE VARCHAR(100);
create index IDX_FILES_REFERENCES_TYPE  on FILES$REFERENCES computed by (REFERENCE_TYPE);





