CREATE GENERATOR GEN_REPORTS$DSO_ID#
create table REPORTS$DSO (
DSO_ID DOM_RECORD_ID not null,
DSO_MONTH VARCHAR (2),
DSO_YEAR VARCHAR (4),
SALES DOM_MONEY,
DSO SMALLINT,
CREATION_USER DOM_CURRENT_USER,
CREATION_DATE DOM_DATE
)#
ALTER TABLE REPORTS$DSO ADD CONSTRAINT PK_REPORTS$DSO PRIMARY KEY (DSO_ID)#

CREATE OR ALTER TRIGGER REPORTS$DSO_BI FOR REPORTS$DSO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.DSO_ID IS NULL) THEN
    NEW.DSO_ID = GEN_ID(GEN_REPORTS$DSO_ID,1);
END#

create index IDX_REPORTS_DSO_MONTH  on REPORTS$DSO computed by (DSO_MONTH)#
create index IDX_REPORTS_DSO_YEAR  on REPORTS$DSO computed by (DSO_YEAR)#

INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('menu_settings-dso_view','all','Dso','Dso','Dso',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('turnover_c','all','omzet','chiffre d''affaires','turnover',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('dso_c','all','Dso','Dso','Dso',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('menu_report_dso','all','Dso','Dso','Dso',0)#


create table REPORTS$SALDO (
AMOUNT DOM_MONEY,
INTERCOMPANY DOM_MONEY,
CREATION_USER DOM_CURRENT_USER,
CREATION_DATE DOM_DATE
)#

create index IDX_REPORTS_SALDO_DATE on REPORTS$SALDO computed by (CREATION_DATE)#
