INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('order_c', 'all', 'Volgorde', 'Ordre', 'Order', 0)#
ALTER TABLE TRAIN ADD ORDER_CYCLE INTEGER#
create index ix_train_order_cycle on TRAIN computed by (ORDER_CYCLE)#
ALTER TABLE FILES$REFERENCES ADD TRAIN_TYPE DOM_REFERENCE#
create index ix_references_train_type on FILES$REFERENCES computed by (TRAIN_TYPE)#
UPDATE FILES$REFERENCES SET TRAIN_TYPE='TRAJECT1'#
DELETE FROM TEKSTEN WHERE CODE = 'BASE_TRAIN_TYPE'#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('BASE_TRAIN_TYPE','all','TRAJECT1','TRAJECT1','TRAJECT1','1')#
UPDATE FILES$DEBTORS SET TRAIN_TYPE='TRAJECT1'#
