create table DEBTOR_SCORE (
    DEBTOR_SCORE_ID DOM_RECORD_ID,
    DEBTOR_ID DOM_RECORD_ID,
    SCORE INT,
    USER_ID DOM_RECORD_ID,
    TIME_STAMP TIMESTAMP
)

INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('debtor_score_c','all','Score','Score','Score',0);
