ALTER TABLE ACCOUNTS$ACCOUNTS ADD VALUTA VARCHAR(10);
ALTER TABLE ACCOUNTS$ACCOUNTS ADD BIC VARCHAR(10);
create index AccountsValuta on ACCOUNTS$ACCOUNTS computed by (VALUTA);
UPDATE ACCOUNTS$ACCOUNTS SET VALUTA='EUR';
