create table ALLOWEDMAILS (
NAME VARCHAR (255),
EMAIL VARCHAR (255),
TYPE VARCHAR(50),
CREATION_USER DOM_CURRENT_USER,
CREATION_DATE DOM_DATE
)#
ALTER TABLE ALLOWEDMAILS ADD CONSTRAINT PK_ALLOWEDMAILS PRIMARY KEY (EMAIL)#



create index IDX_AM_NAME  on ALLOWEDMAILS computed by (NAME)#
create index IDX_AM_EMAIL  on ALLOWEDMAILS computed by (EMAIL)#

INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('menu_settings-allowed-mails_view','all','Email bestemmingen','Detinations email','Email destinations',0)#


ALTER TABLE FILE_DOCUMENTS ADD FILE_ACTION_ID DOM_RECORD_ID#
create index FD_FACTIONS on FILE_DOCUMENTS computed by (FILE_ACTION_ID)#
