create table CURRENCY_RATES (ID DOM_RECORD_ID not null, RATE DECIMAL (10,10), CREATION_DATE DOM_DATE, CREATION_USER DOM_CURRENT_USER, VALUTA VARCHAR(20))#

CREATE GENERATOR GEN_CURRENCY_RATES_ID#

CREATE OR ALTER TRIGGER CURRENCY_RATESBI FOR CURRENCY_RATES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CURRENCY_RATES_ID,1);
END#

INSERT INTO CURRENCY_RATES (RATE, CREATION_DATE, CREATION_USER, VALUTA) VALUES ('1','2016-03-10','ADMIN', 'EUR')#
INSERT INTO CURRENCY_RATES (RATE, CREATION_DATE, CREATION_USER, VALUTA) VALUES ('0.773740234','2016-03-10','ADMIN', 'GBP')#
INSERT INTO CURRENCY_RATES (RATE, CREATION_DATE, CREATION_USER, VALUTA) VALUES ('1.100100000','2016-03-10','ADMIN', 'USD')#

INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('date_currencyrate_c', 'all','Wisselkoers op', 'Taux de change du','Exchange rate on',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('valuta_c', 'all','Valuta', 'Devise','Currency',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('exchengerate_c', 'all','Wisselkoers', 'Taux de change','Exchange rate',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('recent_rate_c', 'all','Recentste wisselkoers', 'Dernier échange','Latest exchange rate',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('exchange_foreign_eur_c', 'all','Vreemde valuta in EUR', 'Devise en EUR','Foreign valuta in EUR',0)#
INSERT INTO TEKSTEN (CODE,NAV,NL,FR,EN,SETTINGS) VALUES ('menu_settings-currency_view', 'all','Wisselkoers', 'Taux de change','Exchange rate',0)#