<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
} else if ($this->deleted === false) {
    print $this->Error($this->G("cant_be_deleted_c"));
}
?>
<?php if (count($this->results)): ?>
    <h3><?php echo count($this->results) ?> resultaten gevonden</h3>
<?php endif ?>
<table id="data" class="tablesorter ws_data_table" width="100%">
    <thead>
    <tr>
        <th><?php $this->T("collector_code_c"); ?></th>
        <th><?php $this->T("name_c"); ?></th>
        <th><?php $this->T("system_standard_c"); ?></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->NAME ?></td>
                <td><?php echo $row->SYSTEM_DEFAULT ?></td>
                <td><a href="<?php echo $this->location() ?>/settings-collectors/edit/id/<?php echo $row->COLLECTOR_ID ?>" ><span title ="<?php $this->T("edit_c") ?>"  class="ui-icon ui-icon-zoomin"></span></td>
                <td>
                    <?php echo $this->Delete($this->location()."/settings-collectors/view/delete/" . $row->COLLECTOR_ID , $row->CODE) ?>
                </td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</table>
