		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
		<div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T('subdebtors_c') ?></h2></div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>

            <tr>
                <th><?php $this->T('name_c') ?></th>
                <th><?php $this->T('referenceclient_c') ?></th>
                <th><?php $this->T('eigen_kredietlimiet_c') ?></th>
                <th><?php $this->T('kredietlimiet_provider_c') ?></th>
                <th><?php $this->T('kredietlimiet_verzekering_c') ?></th>
                <th><?php $this->T('saldo_c') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(count($this->subDebtors) > 0) {
                foreach($this->subDebtors as $debtor) { ?>
                    <tr onclick="window.location = '<?php print $this->location() ?>/debtor-detail/view/debtorId/<?php print $debtor['debtor']->DEBTOR_ID ?>'">
                        <td>
                            <?php for($i = 0; $i < $debtor['depth']; $i++) { ?>
                                &nbsp;&nbsp;&nbsp;<span class="ui-icon ui-icon-carat-1-e" style="display: inline-block; vertical-align: middle;"></span>
                            <?php } ?>
                            <a href="<?php print $this->location() ?>/debtor-detail/view/debtorId/<?php print $debtor['debtor']->DEBTOR_ID ?>" ><?php echo $debtor['debtor']->NAME ?></a>
                        </td>
                        <td><?php echo $debtor['debtor']->REFERENCE ?></td>
                        <td><?php echo $this->Amount($debtor['debtor']->OWN_CREDIT_LIMIT) ?></td>
                        <td><?php echo $this->Amount($debtor['debtor']->PROVIDER_CREDIT_LIMIT) ?></td>
                        <td><?php echo $this->Amount($debtor['debtor']->INSURANCE_CREDIT_LIMIT) ?></td>
                        <td><?php echo $this->Amount($debtor['debtor']->SALDO) ?></td>
                    </tr>
             <?php }
            } ?>
                    </tbody>
                  </table>    
                </div>                          
              </div>