	<script>
		$(document).ready(function(){
   		$('tr.pay').bind('click', function(){

        var record_id   = $(this).attr('id');
		var link        = '<?php echo $this->location() ?>/file-detail/view/fileId/' + record_id;
		
        $.fancybox({
            'width'             : '100%',
            'height'            : '100%',
            'autoScale'         : false,
            'transitionIn'      : 'none',
            'transitionOut'     : 'none',
            'type'              : 'iframe',
            'href'              : link
				});
			});
		});
		</script>


          <div class="aaa-theme-flex-row flex-content-row">
            <div class="aaa-theme-content-widget white-bg col-1 text-center">
              <?php echo $this->searchForm; ?>
            </div>  
          </div>
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative"><h2 class="text-uppercase"><?php $this->T('total_c') ?>: &euro; <?php echo number_format($this->paymentsAllInfoTotal, 2, ',', '.'); ?></h2></div>
                <div class="table-responsive">
                	

                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td><?php $this->T('reference_c') ?></td>
                        <td><?php $this->T('client_c') ?></td>
                        <td><?php $this->T('debtor_c') ?></td>
                        <td><?php $this->T('aanmaakdatum_c') ?></td>
                        <td><?php $this->T('betaaldatum_c') ?></td>
                        <td><?php $this->T('amount_c') ?></td>
                        <td><?php $this->T('voor_c') ?></td>
                        <td><?php $this->T('rekening_c') ?></td>
                        <td><?php $this->T('beschrijving_c') ?></td>
                    
                      </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->paymentsAllInfo as $file): ?>
                    <tr class="pay" id="<?php echo $file->FILE_ID ?>">
                        <td class="center"><?php echo $file->REFERENCE ? $file->REFERENCE : '-' ?></td>
                        <td><?php echo $file->CLIENT_CODE ?></td>
                        <td><?php echo $file->DEBTOR_NAME ?></td>
                        <td><?php echo $this->date($file->CREATION_DATE) ?></td>
                        <td><?php echo $this->date($file->PAYMENT_DATE) ?></td>
                        <td class="right"><?php echo number_format($file->AMOUNT, 2, ',', '.') ?></td>
                        <td><?php echo $file->PAYMENT_FOR ?></td>
                        <td><?php echo $file->ACCOUNT_CODE ?></td>
                        <td class="center"><?php echo $file->JOURNAL_DESCRIPTION ? $file->JOURNAL_DESCRIPTION : '-' ?></td>
                    </tr>
        <?php endforeach; ?>
                      
<script>
    $(function() {
        $("#STARTDATE").datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $("#ENDDATE").datepicker({dateFormat: 'dd/mm/yy'});
    });

</script>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->

