<div class="toggler noprint">
    <div id="searchbox" class="ui-widget-content" style="width: 600px;">
        <?php echo $this->searchForm; ?>
    </div>
</div>
<br>
<h1 style="float: right"><?php $this->T('total_c') ?>: &euro; <?php echo number_format($this->paymentsAllInfoTotal, 2, ',', '.'); ?></h1>
<table class="ws_data_table" style="width: 100%">
    <thead>
        <tr>
            <th><?php $this->T('factuur_c') ?></th>
            <th><?php $this->T('reference_c') ?></th>
            <th><?php $this->T('client_code_c') ?></th>
            <th><?php $this->T('debtor_c') ?></th>
            <th><?php $this->T('aanmaakdatum_c') ?></th>
            <th><?php $this->T('betaaldatum_c') ?></th>
            <th><?php $this->T('bedrag_c') ?></th>
            <th><?php $this->T('voor_c') ?></th>
            <th><?php $this->T('with_commission_c') ?></th>
            <th><?php $this->T('rekening_c') ?></th>
            <th><?php $this->T('beschrijving_c') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paymentsAllInfo as $file): ?>
            <tr>
                <td><?php echo $file->FILE_NR ?></td>
                <td class="center"><?php echo $file->REFERENCE ? $file->REFERENCE : '-' ?></td>
                <td><?php echo $file->CLIENT_CODE ?></td>
                <td><?php echo $file->DEBTOR_NAME ?></td>
                <td><?php echo $this->date($file->CREATION_DATE) ?></td>
                <td><?php echo $this->date($file->PAYMENT_DATE) ?></td>
                <td class="right"><?php echo number_format($file->AMOUNT, 2, ',', '.') ?></td>
                <td><?php echo $file->PAYMENT_FOR ?></td>
                <td><?php echo ($file->WITH_COMMISSION==1) ? "<span class='ui-icon ui-icon-check'></span>" : "<span class='ui-icon ui-icon-close'></span>"; ?></td>
                <td><?php echo $file->ACCOUNT_CODE ?></td>
                <td class="center"><?php echo $file->JOURNAL_DESCRIPTION ? $file->JOURNAL_DESCRIPTION : '-' ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script>
    $(function() {
        $("#STARTDATE").datepicker({dateFormat: 'dd/mm/yy'});
    });
    $(function() {
        $("#ENDDATE").datepicker({dateFormat: 'dd/mm/yy'});
    });

</script>
