
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                	
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <td></td>
                        <?php for ($i=0; $i<=$this->numberOfDays; $i++) : ?>
						<?php $displayDate = date("d/m/Y",strtotime ("+$i day")); ?>
						<td title="<?php echo $displayDate ?>"><?php echo $i; ?></td>
						<?php endfor; ?>
						<td><?php $this->T('total_c'); ?></td>
                      </tr>
                    </thead>
                    <tbody>
					   <?php foreach ($this->followUp as $followUp): ?>
							<tr>
								<?php $rowTotal = 0; ?>
								<td><?php echo $followUp->TRAIN_TYPE ?> : <?php echo $followUp->DESCRIPTION ?></td>
								<?php foreach ($this->counters[$followUp->CODE] as $j => $counter): ?>
									<td>
										<?php if ($counter > 0) : ?>
											<a href="<?php echo $this->location() ?>/traject/list/i/<?php echo $j ?>/serie/1/type/<?php echo $followUp->CODE ?>/collector/<?php echo $this->selectedCollector ?>"><?php echo $counter; ?></a>
										<?php else: ?>
											<?php echo $counter; ?>
										<?php endif; ?>
									</td>
									<?php $rowTotal += $counter; ?>
								<?php endforeach; ?>
								<td><strong><?php echo $rowTotal; ?></strong></td>
							</tr>
						<?php endforeach; ?>
                    </tbody>
                   </table>    
                </div>                          
              </div>
            </div>  
          </div> 
<!-- Second row ends -->