<table class="ws_data_table" width="100%">
    <thead>
        <tr>
            <th><?php $this->T('referenceclient_c') ?></th>
            <th><?php $this->T('name_c') ?></th>
            <th><?php $this->T('state_code_c') ?></th>
            <th><?php $this->T('amount_c') ?></th>
            <th><?php $this->T('total_c') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->results as $index => $file): ?>
            <tr onclick="newscreen('<?php echo $file->DEBTOR_NAME ?>', '<?php echo $this->location() ?>/file-detail/view/index/<?php echo $index; ?>')">
                <td><?php echo $file->REFERENCE ?></td>
                <td><?php echo $file->DEBTOR_NAME ?><br><?php echo $file->DEBTOR_ADDRESS ?><br><?php echo $file->DEBTOR_ZIP_CODE . ' ' . $file->DEBTOR_CITY ?>
                    <?php echo ($file->DEBTOR_TELEPHONE) ? '<br>Tel.: ' . $file->DEBTOR_TELEPHONE : ''; ?>
                    <?php echo ($file->DEBTOR_GSM) ? '<br>Mob.: ' . $file->DEBTOR_GSM : '' ?></td>
                <td><?php echo $file->STATE_CODE ?></td>
                <td class="right"><?php echo number_format($file->AMOUNT, 2, ',', '.') ?></td>
                <td class="right"><?php echo number_format($file->PAYABLE, 2, ',', '.') ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>