
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="aaa-theme-content-widget white-bg col-4 text-center">
              <?php echo $this->costForm; ?>
            </div>  
          </div>
          <div class="aaa-theme-flex-row flex-content-row">
            <div class="col-1">
              <div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="panel-heading aaa-theme-position-relative">
				
				<?php if (count($this->costs)): ?>
				<h2 class="text-uppercase"><?php echo count($this->costs) ?> resultaten gevonden</h2>
				<?php endif; ?>
				
				</div>
                <div class="table-responsive">
                	

                  <table class="table table-striped table-bordered">
                    <thead>
						<tr>
							<td><?php $this->T("created_c"); ?></td>
							<td><?php $this->T("file_c"); ?></td>
							<td><?php $this->T("Code_c"); ?></td>
							<td><?php $this->T("Description_c"); ?></td>
							<td><?php $this->T("amount_c"); ?></td>
							<td><?php $this->T("Invoiceable_c"); ?></td>
						</tr>
                    </thead>
                    <tbody>
    <?php if (!empty($this->costs)) { ?>
        <?php foreach ($this->costs as $row) { ?>
            <?php
            $description = str_replace(PHP_EOL, "<br>", $row->DESCRIPTION);
            // voor speciale kosten(manuele) staat de beschrijving in het veld extra_info
            if ($row->EXTRA_INFO != "") {
                $description = str_replace(PHP_EOL, "<br>", $row->EXTRA_INFO);
            }
            ?>
            <tr>
                <td><?php echo $this->date($row->CREATION_DATE) ?></td>
                <td><?php echo $row->FILE_NR ?></td>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $description ?></td>
                <td><?php echo number_format($row->AMOUNT, '2', ',', '.') ?></td>
                <td><input type="checkbox" <?php echo $row->INVOICEABLE == "1" ? 'checked="checked"' : '' ?> disabled="disabled"></td>

            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="10" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
                      
<script>
    $(function() {
        $("#FROM_DATE").datepicker({dateFormat: 'dd/mm/yy'});
        $("#UNTIL_DATE").datepicker({dateFormat: 'dd/mm/yy'});
    });
</script>
                  </table>    
                </div>                          
              </div>
            </div>  
          </div> <!-- Second row ends -->

