		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
					<tr>
						<td><?php $this->T("creation_date_c"); ?></td>
						<td><?php $this->T("who_c"); ?></td>
						<td><?php $this->T("name_c"); ?></td>
						<td><?php $this->T("address_c"); ?></td>
						<td><?php $this->T("zipcode_c"); ?></td>
						<td><?php $this->T("city_c"); ?></td>
						<td><?php $this->T("mail_c"); ?></td>
						<td><?php $this->T("telephone_c"); ?></td>
						<td><?php $this->T("telefax_c"); ?></td>
					</tr>
    </thead>
	 <tbody>
    <?php if (!empty($this->results)) {?>
        <?php foreach ($this->results as $row) {  ?>
            <tr>
                <td><?php echo $this->date($row->CREATION_DATE) ?></td>
                <td><?php echo $row->CREATION_USER ?></td>
                <td><?php echo $row->NAME ?></td>
                <td><?php echo $row->ADDRESS ?></td>
                <td><?php echo $row->CODE ?></td>
                <td><?php echo $row->CITY ?></td>
                <td><?php echo $row->E_MAIL ?></td>
                <td><?php echo $row->TELEPHONE ?></td>
                <td><?php echo $row->TELEFAX ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>

                    </tbody>
                  </table>    
                </div>                          
              </div>


