<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>
<table id="data" class="tablesorter ws_data_table" width="100%">
    <thead>
        <tr>
            <th><?php $this->T("date_c"); ?></th>
            <th><?php $this->T("createdby_c"); ?></th>
            <th><?php $this->T("description_c"); ?></th>
            <th><?php $this->T("todo_type_c"); ?></th>
            <th><?php $this->T("assigned_to_c"); ?></th>
            <th><?php $this->T("done_c"); ?></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $this->Date($row->CREATION_DATE) ?></td>
                <td><?php echo $row->CREATION_USER ?></td>
                <td><?php echo $row->REMARK ?></td>
                <td><?php echo $row->TODO_TYPE ?></td>
                <td><?php echo $row->ASSIGNED_TO ?></td>
                <td><?php echo $this->Selection($row->DONE) ?></td>
                <td><?php if (!empty($this->manageTasks) or $this->online_user == $row->CREATION_USER ) { ?><a href="<?php echo $this->location() ?>/file-todos/edit/id/<?php echo $row->TODO_ID ?>/index/<?php echo $this->index ?>" ><span title ="<?php $this->T("edit_c") ?>"  class="ui-icon ui-icon-zoomin"></span><?php } ?></td>
                <td><?php if (!empty($this->manageTasks) or $this->online_user == $row->CREATION_USER ) {echo $this->Delete($this->location()."/file-todos/view/delete/".$row->TODO_ID."/index/".$this->index, $row->REMARK); }  ?></td>
                
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="8" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</table>
