<h1>Recent updates</h1>
<pre>
* 26/05/2014 - Correcting files closed
When a selection of 'include closed files' is made on de general files screen.  Only open files will be shown

* 12/05/2014 - Adding total to letter details
On printed letters, a total has been added to the invoices list(Attachment)
Some bug fixes on convertion of special chars.

* 30/04/2014 8:55 - Adding Updates system
In the menu Settings -> updates, you can now see it there are recent updates.

* 30/04/2014 8:22 - Print letters
Changes to letters system.  You can now specify positions of logo's, textbloks, etc....
This can be done in the menu setting -> Text Settings, where you can change the settings of 'LETTERS_SETTINGS'

* 29/04/2014 10:00 - Minor bug correction
On the general -> files page, the graph was not showing payed versus open.  This has been corrected.

</pre>


</p>