<table id="data" class="tablesorter ws_data_table" width="100%">
    <thead>
        <tr>
            <th><?php $this->T("referenceclient_c"); ?></th>
            <th><?php $this->T("state_code_c"); ?></th>
            <th><?php $this->T("last_action_date_c"); ?></th>
            <th><?php $this->T("amount_c"); ?></th>
            <th><?php $this->T("payable_c"); ?></th>
            <th></th>
        </tr>
    </thead>
    <?php if (!empty($this->results)) { $index=0;?>
        <?php foreach ($this->results as $row) {  ?>
            <tr>
                <td><?php echo $row->REFERENCE ?></td>
                <td><?php echo $row->STATE_CODE ?></td>
                <td><?php echo $this->date($row->LAST_ACTION_DATE) ?></td>
                <td><?php echo $this->amount($row->TOTAL) ?></td>
                <td><?php echo $this->amount($row->PAYABLE) ?></td>
                <td><a title ="<?php $this->T("view_file_c") ?>" href="<?php echo $this->location() ?>/file-detail/view/fileId/<?php echo $row->fileId ?>" class="ui-icon ui-icon-zoomin"></a></td>
            </tr>
        <?php $index++;} ?>
    <?php } else { ?>
        <tr>
            <td colspan="5" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</table>

