<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>
<table id="data" class="tablesorter ws_data_table" width="100%">
    <thead>
        <tr>
            <th><?php $this->T("payment_date_c"); ?></th>
            <th><?php $this->T("creation_date_c"); ?></th>
            <th><?php $this->T("amount_c"); ?></th>
            <th><?php $this->T("invoice_c"); ?></th>
            <th><?php $this->T("payment_for_c"); ?></th>
            <th><?php $this->T("account_c"); ?></th>
            <th><?php $this->T("description_c"); ?></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $this->Date($row->PAYMENT_DATE) ?></td>
                <td><?php echo $this->Date($row->CREATION_DATE) ?></td>
                <td align="right"><?php echo $this->Amount($row->AMOUNT) ?></td>
                <td align="right"><?php echo $row->REFERENCE ?></td>
                <td><?php echo $row->PAYMENT_FOR ?></td>
                <td><?php echo $row->ACCOUNT_CODE ?></td>
                <td><?php echo $row->JOURNAL_DESCRIPTION ?></td>
                <td><?php if (!empty($this->managePayments)) { ?><a href="<?php echo $this->location() ?>/file-payments/edit/id/<?php echo $row->PAYMENT_ID ?>/index/<?php echo $this->index ?>" ><span title ="<?php $this->T("edit_c") ?>"  class="ui-icon ui-icon-zoomin"></span><?php } ?></td>
                <td><?php if (!empty($this->managePayments)) { ?><?php echo $this->Delete($this->location()."/file-payments/view/delete/".$row->PAYMENT_ID."/index/".$this->index, $this->Amount($row->AMOUNT)) ?><?php } ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="10" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</table>

