<?php
if ($this->deleted) {
    print $this->Ok($this->G("deleted_c"));
}
?>
		<div class="panel panel-default aaa-theme-content-widget white-bg no-padding aaa-theme-overflow-hidden">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
						<td><?php $this->T("payment_date_c"); ?></td>
						<td><?php $this->T("creation_date_c"); ?></td>
						<td><?php $this->T("amount_c"); ?></td>
						<td><?php $this->T("invoice_c"); ?></td>
						<td><?php $this->T("payment_for_c"); ?></td>
						<td><?php $this->T("account_c"); ?></td>
						<td><?php $this->T("description_c"); ?></td>
						<td></td>
						<td></td>
                       </tr>
                    </thead>
                    <tbody>
    <?php if (!empty($this->results)) { ?>
        <?php foreach ($this->results as $row) { ?>
            <tr>
                <td><?php echo $this->Date($row->PAYMENT_DATE) ?></td>
                <td><?php echo $this->Date($row->CREATION_DATE) ?></td>
                <td align="right"><?php echo $this->Amount($row->AMOUNT) ?></td>
                <td align="right"><?php echo $row->REFERENCE ?></td>
                <td><?php echo $row->PAYMENT_FOR ?></td>
                <td><?php echo $row->ACCOUNT_CODE ?></td>
                <td><?php echo $row->JOURNAL_DESCRIPTION ?></td>
                <td><?php if (!empty($this->managePayments)) { ?><a href="<?php echo $this->location() ?>/file-payments/edit/id/<?php echo $row->PAYMENT_ID ?>/fileId/<?php echo $this->fileId ?>" ><li class="fa fa-search-plus fa-fw"></li><?php } ?></td>
                <td><?php if (!empty($this->managePayments)) { ?><?php echo $this->Delete($this->location()."/file-payments/view/delete/".$row->PAYMENT_ID."/fileId/".$this->fileId, $this->Amount($row->AMOUNT)) ?><?php } ?></td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="10" class="no_results">
                <?php $this->T("no_results_c"); ?>
            </td>
        </tr>
    <?php } ?>
</tbody>
                  </table>    
                </div>                          
              </div>


